// ==++==
//
//   
//    Copyright (c) 2002 Microsoft Corporation.  All rights reserved.
//   
//    The use and distribution terms for this software are contained in the file
//    named license.txt, which can be found in the root of this distribution.
//    By using this software in any fashion, you are agreeing to be bound by the
//    terms of this license.
//   
//    You must not remove this notice, or any other, from this software.
//   
//
// ==--==
// ===========================================================================
// File: errors.h
//
// Contains a list of all the warnings and errors in the compiler.
//
// ===========================================================================

#ifndef ERRORDEF
#error Must define ERRORDEF macro before including errors.h
#endif

// NOTE:  Warnings, errors, and fatal errors are determined by the
//        warning level value as follows:
//
//          0   = ERROR_ERROR
//          >0  = ERROR_WARNING
//          -1  = ERROR_FATAL
//
//     Error  Warning
//     Number, Level,      Error name,                    Resource name
ERRORDEF(   1, -1,    FTL_InternalError,                  IDS_InternalError)

ERRORDEF(   3, -1,    FTL_NoMemory,                       IDS_NoMemory)
ERRORDEF(   4, 0,     ERR_WarningAsError,                 IDS_WarningAsError)
ERRORDEF(   5, 0,     ERR_MissingOptionArg,               IDS_MissingOptionArg)
ERRORDEF(   6, 0,     ERR_NoMetadataFile,                 IDS_NoMetadataFile)
ERRORDEF(   7, -1,    FTL_ComPlusInit,                    IDS_ComPlusInit)
ERRORDEF(   8, -1,    FTL_MetadataImportFailure,          IDS_MetadataImportFailure)
ERRORDEF(   9, -1,    FTL_MetadataCantOpenFile,           IDS_MetadataCantOpenFile)
ERRORDEF(   9, 0,     ERR_MetadataCantOpenFile,           IDS_MetadataCantOpenFile)
ERRORDEF(  10, 0,     ERR_NamespaceTypeConflict,          IDS_NamespaceTypeConflict)
ERRORDEF(  11, 0,     ERR_CantImportBase,                 IDS_CantImportBase)
ERRORDEF(  12, 0,     ERR_NoTypeDef,                      IDS_NoTypeDef)
ERRORDEF(  13, -1,    FTL_MetadataEmitFailure,            IDS_MetadataEmitFailure)
ERRORDEF(  14, -1,    FTL_RequiredFileNotFound,           IDS_RequiredFileNotFound)
ERRORDEF(  15, 0,     ERR_ClassNameTooLong,               IDS_ClassNameTooLong)
ERRORDEF(  16, 0,     ERR_OutputWriteFailed,              IDS_OutputWriteFailed)
ERRORDEF(  17, 0,     ERR_MultipleEntryPoints,            IDS_MultipleEntryPoints)
ERRORDEF(  18, 0,     ERR_UnimplementedOp,                IDS_UnimplementedOp)
ERRORDEF(  19, 0,     ERR_BadBinaryOps,                   IDS_BadBinaryOps)
ERRORDEF(  20, 0,     ERR_IntDivByZero,                   IDS_IntDivByZero)
ERRORDEF(  21, 0,     ERR_BadIndexLHS,                    IDS_BadIndexLHS)
ERRORDEF(  22, 0,     ERR_BadIndexCount,                  IDS_BadIndexCount)
ERRORDEF(  23, 0,     ERR_BadUnaryOp,                     IDS_BadUnaryOp)

ERRORDEF(  25, 0,     ERR_NoStdLib,                       IDS_NoStdLib)
ERRORDEF(  26, 0,     ERR_ThisInStaticMeth,               IDS_ThisInStaticMeth)
ERRORDEF(  27, 0,     ERR_ThisInBadContext,               IDS_ThisInBadContext)
ERRORDEF(  28, 4,     WRN_InvalidMainSig,                 IDS_InvalidMainSig)
ERRORDEF(  29, 0,     ERR_NoImplicitConv,                 IDS_NoImplicitConv)
ERRORDEF(  30, 0,     ERR_NoExplicitConv,                 IDS_NoExplicitConv)
ERRORDEF(  31, 0,     ERR_ConstOutOfRange,                IDS_ConstOutOfRange)
ERRORDEF(  32, 0,     ERR_IncBuildWrite,                  IDS_IncBuildWrite)
ERRORDEF(  33, 0,     ERR_IncBuildWriteIO,                IDS_IncBuildWriteIO)
ERRORDEF(  34, 0,     ERR_AmbigBinaryOps,                 IDS_AmbigBinaryOps)
ERRORDEF(  35, 0,     ERR_AmbigUnaryOp,                   IDS_AmbigUnaryOp)
ERRORDEF(  36, 0,     ERR_InAttrOnOutParam,               IDS_InAttrOnOutParam)
ERRORDEF(  37, 0,     ERR_ValueCantBeNull,                IDS_ValueCantBeNull)
ERRORDEF(  38, 0,     ERR_WrongNestedThis,                IDS_WrongNestedThis)
ERRORDEF(  39, 0,     ERR_NoExplicitBuiltinConv,          IDS_NoExplicitBuiltinConv)

ERRORDEF(  40, -1,    FTL_DebugInit,                      IDS_DebugInit)
ERRORDEF(  41, -1,    FTL_DebugEmitFailure,               IDS_DebugEmitFailure)
ERRORDEF(  42, -1,    FTL_DebugInitFile,                  IDS_DebugInitFile)
ERRORDEF(  43, -1,    FTL_BadPDBFormat,                   IDS_BadPDBFormat)

ERRORDEF(  50, 0,     ERR_BadVisReturnType,               IDS_BadVisReturnType)
ERRORDEF(  51, 0,     ERR_BadVisParamType,                IDS_BadVisParamType)
ERRORDEF(  52, 0,     ERR_BadVisFieldType,                IDS_BadVisFieldType)
ERRORDEF(  53, 0,     ERR_BadVisPropertyType,             IDS_BadVisPropertyType)
ERRORDEF(  54, 0,     ERR_BadVisIndexerReturn,            IDS_BadVisIndexerReturn)
ERRORDEF(  55, 0,     ERR_BadVisIndexerParam,             IDS_BadVisIndexerParam)
ERRORDEF(  56, 0,     ERR_BadVisOpReturn,                 IDS_BadVisOpReturn)
ERRORDEF(  57, 0,     ERR_BadVisOpParam,                  IDS_BadVisOpParam)
ERRORDEF(  58, 0,     ERR_BadVisDelegateReturn,           IDS_BadVisDelegateReturn)
ERRORDEF(  59, 0,     ERR_BadVisDelegateParam,            IDS_BadVisDelegateParam)
ERRORDEF(  60, 0,     ERR_BadVisBaseClass,                IDS_BadVisBaseClass)
ERRORDEF(  61, 0,     ERR_BadVisBaseInterface,            IDS_BadVisBaseInterface)
ERRORDEF(  65, 0,     ERR_EventNeedsBothAccessors,        IDS_EventNeedsBothAccessors)
ERRORDEF(  66, 0,     ERR_EventNotDelegate,               IDS_EventNotDelegate)
ERRORDEF(  67, 3,     WRN_UnreferencedEvent,              IDS_UnreferencedEvent)
ERRORDEF(  68, 0,     ERR_InterfaceEventInitializer,      IDS_InterfaceEventInitializer)
ERRORDEF(  69, 0,     ERR_EventPropertyInInterface,       IDS_EventPropertyInInterface)
ERRORDEF(  70, 0,     ERR_BadEventUsage,                  IDS_BadEventUsage)
ERRORDEF(  71, 0,     ERR_ExplicitEventFieldImpl,         IDS_ExplicitEventFieldImpl)
ERRORDEF(  72, 0,     ERR_CantOverrideNonEvent,           IDS_CantOverrideNonEvent)
ERRORDEF(  73, 0,     ERR_AddRemoveMustHaveBody,          IDS_AddRemoveMustHaveBody)
ERRORDEF(  74, 0,     ERR_AbstractEventInitializer,       IDS_AbstractEventInitializer)
ERRORDEF(  75, 0,     ERR_PossibleBadNegCast,             IDS_PossibleBadNegCast)
ERRORDEF(  76, 0,     ERR_ReservedEnumerator,             IDS_ReservedEnumerator)
ERRORDEF(  77, 0,     ERR_AsMustHaveReferenceType,        IDS_AsMustHaveReferenceType)
ERRORDEF(  78, 4,     WRN_LowercaseEllSuffix,             IDS_LowercaseEllSuffix)
ERRORDEF(  79, 0,     ERR_BadEventUsageNoField,           IDS_BadEventUsageNoField)

ERRORDEF(100, 0,     ERR_DuplicateParamName,             IDS_DuplicateParamName)
ERRORDEF(101, 0,     ERR_DuplicateNameInNS,              IDS_DuplicateNameInNS)
ERRORDEF(102, 0,     ERR_DuplicateNameInClass,           IDS_DuplicateNameInClass)
ERRORDEF(103, 0,     ERR_NameNotInContext,               IDS_NameNotInContext)
ERRORDEF(104, 0,     ERR_AmbigContext,                   IDS_AmbigContext)
ERRORDEF(105, 3,     WRN_DuplicateUsing,                 IDS_DuplicateUsing)
ERRORDEF(106, 0,     ERR_BadMemberFlag,                  IDS_BadMemberFlag)
ERRORDEF(107, 0,     ERR_BadMemberProtection,            IDS_BadMemberProtection)
ERRORDEF(108, 2,     WRN_NewRequired,                    IDS_NewRequired)
ERRORDEF(109, 4,     WRN_NewNotRequired,                 IDS_NewNotRequired)
ERRORDEF(110, 0,     ERR_CircConstValue,                 IDS_CircConstValue)
ERRORDEF(111, 0,     ERR_MemberAlreadyExists,            IDS_MemberAlreadyExists)
ERRORDEF(112, 0,     ERR_StaticNotVirtual,               IDS_StaticNotVirtual)
ERRORDEF(113, 0,     ERR_OverrideNotNew,                 IDS_OverrideNotNew)
ERRORDEF(114, 2,     WRN_NewOrOverrideExpected,          IDS_NewOrOverrideExpected)
ERRORDEF(115, 0,     ERR_OverrideNotExpected,            IDS_OverrideNotExpected)
ERRORDEF(116, 0,     ERR_NamespaceUnexpected,            IDS_NamespaceUnexpected)
ERRORDEF(117, 0,     ERR_NoSuchMember,                   IDS_NoSuchMember)
ERRORDEF(118, 0,     ERR_BadSKknown,                     IDS_BadSKknown)
ERRORDEF(119, 0,     ERR_BadSKunknown,                   IDS_BadSKunknown)
ERRORDEF(120, 0,     ERR_ObjectRequired,                 IDS_ObjectRequired)
ERRORDEF(121, 0,     ERR_AmbigCall,                      IDS_AmbigCall)
ERRORDEF(122, 0,     ERR_BadAccess,                      IDS_BadAccess)
ERRORDEF(123, 0,     ERR_InvalidCall,                    IDS_InvalidCall)
//ERRORDEF(124, 0,     ERR_InvalidName,                    IDS_InvalidName)         // Not Used
//ERRORDEF(125, 0,     ERR_RetBadType,                     IDS_RetBadType)          // Not Used
ERRORDEF(126, 0,     ERR_RetObjectRequired,              IDS_RetObjectRequired)
ERRORDEF(127, 0,     ERR_RetNoObjectRequired,            IDS_RetNoObjectRequired)
ERRORDEF(128, 0,     ERR_LocalDuplicate,                 IDS_LocalDuplicate)
//ERRORDEF(129, 0,     ERR_LocalShadow,                    IDS_LocalShadow)         // Not used
//ERRORDEF(130, 0,     ERR_LocalShadowLocal,               IDS_LocalShadowLocal)    // Not used
ERRORDEF(131, 0,     ERR_AssgLvalueExpected,             IDS_AssgLvalueExpected)
ERRORDEF(132, 0,     ERR_StaticConstParam,               IDS_StaticConstParam)
ERRORDEF(133, 0,     ERR_NotConstantExpression,          IDS_NotConstantExpression)
ERRORDEF(134, 0,     ERR_IllegalQualifiedNamespace,      IDS_IllegalQualifiedNamespace)
ERRORDEF(135, 0,     ERR_NameIllegallyOverrides,         IDS_NameIllegallyOverrides)
ERRORDEF(136, 0,     ERR_LocalIllegallyOverrides,        IDS_LocalIllegallyOverrides)
//ERRORDEF(137, 0,     ERR_BadUsingType,                   IDS_BadUsingType)    // Not Used
ERRORDEF(138, 0,     ERR_BadUsingNamespace,              IDS_BadUsingNamespace)
ERRORDEF(139, 0,     ERR_NoBreakOrCont,                  IDS_NoBreakOrCont)
ERRORDEF(140, 0,     ERR_DuplicateLabel,                 IDS_DuplicateLabel)
//ERRORDEF(141, 0,     ERR_FeatureNYI,                     IDS_FeatureNYI)
//ERRORDEF(142, 0,     ERR_NoDefaultConstructor,           IDS_NoDefaultConstructor)    // Not Used
ERRORDEF(143, 0,     ERR_NoConstructors,                 IDS_NoConstructors)
ERRORDEF(144, 0,     ERR_NoNewAbstract,                  IDS_NoNewAbstract)
ERRORDEF(145, 0,     ERR_ConstValueRequired,             IDS_ConstValueRequired)
ERRORDEF(146, 0,     ERR_CircularBase,                   IDS_CircularBase)
//ERRORDEF(147, 0,     ERR_NoThis,                         IDS_NoThis)              // Not Used
ERRORDEF(148, 0,     ERR_BadDelegateConstructor,         IDS_BadDelegateConstructor)
ERRORDEF(149, 0,     ERR_MethodNameExpected,             IDS_MethodNameExpected)
ERRORDEF(150, 0,     ERR_ConstantExpected,               IDS_ConstantExpected)
ERRORDEF(151, 0,     ERR_IntegralTypeValueExpected,      IDS_IntegralTypeValueExpected)
ERRORDEF(152, 0,     ERR_DuplicateCaseLabel,             IDS_DuplicateCaseLabel)
ERRORDEF(153, 0,     ERR_InvalidGotoCase,                IDS_InvalidGotoCase)
ERRORDEF(154, 0,     ERR_PropertyLacksGet,               IDS_PropertyLacksGet)
ERRORDEF(155, 0,     ERR_BadExceptionType,               IDS_BadExceptionType)
ERRORDEF(156, 0,     ERR_BadEmptyThrow,                  IDS_BadEmptyThrow)
ERRORDEF(157, 0,     ERR_BadFinallyLeave,                IDS_BadFinallyLeave)
ERRORDEF(158, 0,     ERR_LabelShadow,                    IDS_LabelShadow)
ERRORDEF(159, 0,     ERR_LabelNotFound,                  IDS_LabelNotFound)
ERRORDEF(160, 0,     ERR_UnreachableCatch,               IDS_UnreachableCatch)
ERRORDEF(161, 0,     ERR_ReturnExpected,                 IDS_ReturnExpected)
ERRORDEF(162, 2,     WRN_UnreachableCode,                IDS_UnreachableCode)
ERRORDEF(163, 0,     ERR_SwitchFallThrough,              IDS_SwitchFallThrough)
ERRORDEF(164, 2,     WRN_UnreferencedLabel,              IDS_UnreferencedLabel)
ERRORDEF(165, 0,     ERR_UseDefViolation,                IDS_UseDefViolation)
//ERRORDEF(166, 0,     ERR_SwitchFallInto,                 IDS_SwitchFallInto)      // Not Used
ERRORDEF(167, 0,     ERR_NoInvoke,                       IDS_NoInvoke)
ERRORDEF(168, 3,     WRN_UnreferencedVar,                IDS_UnreferencedVar)
ERRORDEF(169, 3,     WRN_UnreferencedField,              IDS_UnreferencedField)
ERRORDEF(170, 0,     ERR_UseDefViolationField,           IDS_UseDefViolationField)
ERRORDEF(171, 0,     ERR_UnassignedThis,                 IDS_UnassignedThis)
ERRORDEF(172, 0,     ERR_AmbigQM,                        IDS_AmbigQM)
ERRORDEF(173, 0,     ERR_InvalidQM,                      IDS_InvalidQM)
ERRORDEF(174, 0,     ERR_NoBaseClass,                    IDS_NoBaseClass)
ERRORDEF(175, 0,     ERR_BaseIllegal,                    IDS_BaseIllegal)
ERRORDEF(176, 0,     ERR_ObjectProhibited,               IDS_ObjectProhibited)
ERRORDEF(177, 0,     ERR_ParamUnassigned,                IDS_ParamUnassigned)
ERRORDEF(178, 0,     ERR_InvalidArray,                   IDS_InvalidArray)
ERRORDEF(179, 0,     ERR_ExternHasBody,                  IDS_ExternHasBody)
ERRORDEF(180, 0,     ERR_AbstractAndExtern,              IDS_AbstractAndExtern)
//ERRORDEF(181, 0,     ERR_UnknownAttribute,               IDS_UnknownAttribute)
ERRORDEF(182, 0,     ERR_BadAttributeParam,              IDS_BadAttributeParam)
ERRORDEF(183, 1,     WRN_IsAlwaysTrue,                   IDS_IsAlwaysTrue)
ERRORDEF(184, 1,     WRN_IsAlwaysFalse,                  IDS_IsAlwaysFalse)
ERRORDEF(185, 0,     ERR_LockNeedsReference,             IDS_LockNeedsReference)
ERRORDEF(186, 0,     ERR_NullNotValid,                   IDS_NullNotValid)
ERRORDEF(187, 0,     ERR_NoSuchOperator,                 IDS_NoSuchOperator)
ERRORDEF(188, 0,     ERR_UseDefViolationThis,            IDS_UseDefViolationThis)
ERRORDEF(189, 2,     WRN_FeatureNYI,                     IDS_FeatureNYI2)
ERRORDEF(190, 0,     ERR_ArgsInvalid,                    IDS_ArgsInvalid)
ERRORDEF(191, 0,     ERR_AssgReadonly,                   IDS_AssgReadonly)
ERRORDEF(192, 0,     ERR_RefReadonly,                    IDS_RefReadonly)
ERRORDEF(193, 0,     ERR_PtrExpected,                    IDS_PtrExpected)

ERRORDEF(196, 0,     ERR_PtrIndexSingle,                 IDS_PtrIndexSingle)
ERRORDEF(197, 0,     ERR_ByRefNonAgileField,             IDS_ByRefNonAgileField)
ERRORDEF(198, 0,     ERR_AssgReadonlyStatic,             IDS_AssgReadonlyStatic)
ERRORDEF(199, 0,     ERR_RefReadonlyStatic,              IDS_RefReadonlyStatic)
ERRORDEF(200, 0,     ERR_AssgReadonlyProp,               IDS_AssgReadonlyProp)
ERRORDEF(201, 0,     ERR_IllegalStatement,               IDS_IllegalStatement)
ERRORDEF(202, 0,     ERR_BadGetEnumerator,               IDS_BadGetEnumerator)
//ERRORDEF(203, 0,     ERR_BadMethodObject,                IDS_BadMethodObject)
ERRORDEF(204, 0,     ERR_TooManyLocals,                  IDS_TooManyLocals)
ERRORDEF(205, 0,     ERR_AbstractBaseCall,               IDS_AbstractBaseCall)
ERRORDEF(206, 0,     ERR_RefProperty,                    IDS_RefProperty)
//ERRORDEF(207, 1,     WRN_UnsafeProp,                     IDS_UnsafeProp)
ERRORDEF(208, 0,     ERR_ManagedAddr,                    IDS_ManagedAddr)
ERRORDEF(209, 0,     ERR_BadFixedInitType,               IDS_BadFixedInitType)
ERRORDEF(210, 0,     ERR_FixedMustInit,                  IDS_FixedMustInit)
ERRORDEF(211, 0,     ERR_InvalidAddrOp,                  IDS_InvalidAddrOp)
ERRORDEF(212, 0,     ERR_FixedNeeded,                    IDS_FixedNeeded)
ERRORDEF(213, 0,     ERR_FixedNotNeeded,                 IDS_FixedNotNeeded)
ERRORDEF(214, 0,     ERR_UnsafeNeeded,                   IDS_UnsafeNeeded)
ERRORDEF(215, 0,     ERR_OpTFRetType,                    IDS_OpTFRetType)
ERRORDEF(216, 0,     ERR_OperatorNeedsMatch,             IDS_OperatorNeedsMatch)
ERRORDEF(217, 0,     ERR_BadBoolOp,                      IDS_BadBoolOp)
ERRORDEF(218, 0,     ERR_MustHaveOpTF,                   IDS_MustHaveOpTF)
ERRORDEF(219, 3,     WRN_UnreferencedVarAssg,            IDS_UnreferencedVarAssg)
ERRORDEF(220, 0,     ERR_CheckedOverflow,                IDS_CheckedOverflow)
ERRORDEF(221, 0,     ERR_ConstOutOfRangeChecked,         IDS_ConstOutOfRangeChecked)
//ERRORDEF(222, 0,     ERR_UnknownRankAddress,             IDS_UnknownRankAddress)
//ERRORDEF(223, 0,     ERR_NoNullCase,                     IDS_NoNullCase)
ERRORDEF(224, 0,     ERR_VarargsAndParams,               IDS_VarargsAndParams)
ERRORDEF(225, 0,     ERR_ParamsMustBeArray,              IDS_ParamsMustBeArray)
ERRORDEF(226, 0,     ERR_IllegalArglist,                 IDS_IllegalArglist)
ERRORDEF(227, 0,     ERR_IllegalUnsafe,                  IDS_IllegalUnsafe)
ERRORDEF(228, 0,     ERR_NoAccessibleMember,             IDS_NoAccessibleMember)
ERRORDEF(229, 0,     ERR_AmbigMethProp,                  IDS_AmbigMethProp)
ERRORDEF(230, 0,     ERR_BadForeachDecl,                 IDS_BadForeachDecl)
ERRORDEF(231, 0,     ERR_ParamsVarargsLast,              IDS_ParamsVarargsLast)
//ERRORDEF(232, 0,     ERR_AmbigArrayIndex,                IDS_AmbigArrayIndex)
ERRORDEF(233, 0,     ERR_SizeofUnsafe,                   IDS_SizeofUnsafe)
ERRORDEF(234, 0,     ERR_TypeNameNotFound,               IDS_TypeNameNotFound)
ERRORDEF(235, 0,     ERR_VarargDelegate,                 IDS_VarargDelegate)
ERRORDEF(236, 0,     ERR_FieldInitRefNonstatic,          IDS_FieldInitRefNonstatic)
ERRORDEF(237, 0,     ERR_VarargIndexer,                  IDS_VarargIndexer)
ERRORDEF(238, 0,     ERR_SealedNonOverride,              IDS_SealedNonOverride)
ERRORDEF(239, 0,     ERR_CantOverrideSealed,             IDS_CantOverrideSealed)
ERRORDEF(241, 0,     ERR_NoDefaultArgs,                  IDS_NoDefaultArgs)
ERRORDEF(242, 0,     ERR_VoidError,                      IDS_VoidError)
ERRORDEF(243, 0,     ERR_ConditionalOnOverride,          IDS_ConditionalOnOverride)
ERRORDEF(244, 0,     ERR_PointerInAsOrIs,                IDS_PointerInAsOrIs)
ERRORDEF(245, 0,     ERR_CallingFinalizeDepracated,      IDS_CallingFinalizeDepracated)
ERRORDEF(246, 0,     ERR_SingleTypeNameNotFound,         IDS_SingleTypeNameNotFound)
ERRORDEF(247, 0,     ERR_NegativeStackAllocSize,         IDS_NegativeStackAllocSize)
ERRORDEF(248, 0,     ERR_NegativeArraySize,              IDS_NegativeArraySize)
ERRORDEF(249, 0,     ERR_OverrideFinalizeDepracated,     IDS_OverrideFinalizeDepracated)
ERRORDEF(250, 0,     ERR_CallingBaseFinalizeDeprecated,  IDS_CallingBaseFinalizeDeprecated)
ERRORDEF(251, 2,     WRN_NegativeArrayIndex,             IDS_NegativeArrayIndex)
ERRORDEF(252, 2,     WRN_BadRefCompareLeft,              IDS_BadRefCompareLeft)
ERRORDEF(253, 2,     WRN_BadRefCompareRight,             IDS_BadRefCompareRight)
ERRORDEF(254, 0,     ERR_BadCastInFixed,                 IDS_BadCastInFixed)
ERRORDEF(255, 0,     ERR_StackallocInCatchFinally,       IDS_StackallocInCatchFinally)

ERRORDEF(500, 0,     ERR_AbstractHasBody,                IDS_AbstractHasBody)
ERRORDEF(501, 0,     ERR_ConcreteMissingBody,            IDS_ConcreteMissingBody)
ERRORDEF(502, 0,     ERR_AbstractAndSealed,              IDS_AbstractAndSealed)
ERRORDEF(503, 0,     ERR_AbstractNotVirtual,             IDS_AbstractNotVirtual)
ERRORDEF(504, 0,     ERR_StaticConstant,                 IDS_StaticConstant)
ERRORDEF(505, 0,     ERR_CantOverrideNonFunction,        IDS_CantOverrideNonFunction)
ERRORDEF(506, 0,     ERR_CantOverrideNonVirtual,         IDS_CantOverrideNonVirtual)
ERRORDEF(507, 0,     ERR_CantChangeAccessOnOverride,     IDS_CantChangeAccessOnOverride)
ERRORDEF(508, 0,     ERR_CantChangeReturnTypeOnOverride, IDS_CantChangeReturnTypeOnOverride)
ERRORDEF(509, 0,     ERR_CantDeriveFromSealedClass,      IDS_CantDeriveFromSealedClass)
//ERRORDEF(510, 0,     ERR_RelatedSymbolError,             IDS_RelatedSymbolError)
//ERRORDEF(511, 4,     WRN_RelatedSymbolWarning,           IDS_RelatedSymbolWarning)
// Error 512 not used
ERRORDEF(513, 0,     ERR_AbstractInConcreteClass,        IDS_AbstractInConcreteClass)
ERRORDEF(514, 0,     ERR_StaticConstructorWithExplicitConstructorCall,  IDS_StaticConstructorWithExplicitConstructorCall)
ERRORDEF(515, 0,     ERR_StaticConstructorWithAccessModifiers,          IDS_StaticConstructorWithAccessModifiers)
ERRORDEF(516, 0,     ERR_RecursiveConstructorCall,       IDS_RecursiveConstructorCall)
ERRORDEF(517, 0,     ERR_ObjectCallingBaseConstructor,   IDS_ObjectCallingBaseConstructor)
ERRORDEF(518, 0,     ERR_PredefinedTypeNotFound,         IDS_PredefinedTypeNotFound)
ERRORDEF(519, 0,     ERR_PredefinedTypeBadNamespace,     IDS_PredefinedTypeBadNamespace)
ERRORDEF(520, 0,     ERR_PredefinedTypeBadType,          IDS_PredefinedTypeBadType)
// Error 521 not used
ERRORDEF(522, 0,     ERR_StructWithBaseConstructorCall,  IDS_StructWithBaseConstructorCall)
ERRORDEF(523, 0,     ERR_StructLayoutCycle,              IDS_StructLayoutCycle)
ERRORDEF(524, 0,     ERR_InterfacesCannotContainTypes,   IDS_InterfacesCannotContainTypes)
ERRORDEF(525, 0,     ERR_InterfacesCantContainFields,    IDS_InterfacesCantContainFields)
ERRORDEF(526, 0,     ERR_InterfacesCantContainConstructors, IDS_InterfacesCantContainConstructors)
ERRORDEF(527, 0,     ERR_NonInterfaceInInterfaceList,    IDS_NonInterfaceInInterfaceList)
ERRORDEF(528, 0,     ERR_DuplicateInterfaceInBaseList,   IDS_DuplicateInterfaceInBaseList)
ERRORDEF(529, 0,     ERR_CycleInInterfaceInheritance,    IDS_CycleInInterfaceInheritance)
// ERRORDEF(530, 0,     ERR_InterfaceMemberCantHideInheritedMember,        IDS_InterfaceMemberCantHideInheritedMember)
ERRORDEF(531, 0,     ERR_InterfaceMemberHasBody,         IDS_InterfaceMemberHasBody)
// ERRORDEF(532, 0,     ERR_ConflictBetweenInheritedInterfaceMembers,      IDS_ConflictBetweenInheritedInterfaceMembers)
ERRORDEF(533, 0,     ERR_HidingAbstractMethod,           IDS_HidingAbstractMethod)
ERRORDEF(534, 0,     ERR_UnimplementedAbstractMethod,    IDS_UnimplementedAbstractMethod)
ERRORDEF(535, 0,     ERR_UnimplementedInterfaceMember,   IDS_UnimplementedInterfaceMember)
ERRORDEF(536, 0,     ERR_CloseUnimplementedInterfaceMember,             IDS_CloseUnimplementedInterfaceMember)
ERRORDEF(537, 0,     ERR_ObjectCantHaveBases,            IDS_ObjectCantHaveBases)
ERRORDEF(538, 0,     ERR_ExplicitInterfaceImplementationNotInterface,   IDS_ExplicitInterfaceImplementationNotInterface)
ERRORDEF(539, 0,     ERR_InterfaceMemberNotFound,        IDS_InterfaceMemberNotFound)
ERRORDEF(540, 0,     ERR_ClassDoesntImplementInterface,  IDS_ClassDoesntImplementInterface)
ERRORDEF(541, 0,     ERR_ExplicitInterfaceImplementationInNonClassOrStruct, IDS_ExplicitInterfaceImplementationInNonClassOrStruct)
ERRORDEF(542, 0,     ERR_MemberNameSameAsType,           IDS_MemberNameSameAsType)
ERRORDEF(543, 0,     ERR_EnumeratorOverflow,             IDS_EnumeratorOverflow)
ERRORDEF(544, 0,     ERR_CantOverrideNonProperty,        IDS_CantOverrideNonProperty)
ERRORDEF(545, 0,     ERR_NoGetToOverride,                IDS_NoGetToOverride)
ERRORDEF(546, 0,     ERR_NoSetToOverride,                IDS_NoSetToOverride)
ERRORDEF(547, 0,     ERR_PropertyCantHaveVoidType,       IDS_PropertyCantHaveVoidType)
ERRORDEF(548, 0,     ERR_PropertyWithNoAccessors,        IDS_PropertyWithNoAccessors)
ERRORDEF(549, 0,     ERR_NewVirtualInSealed,             IDS_NewVirtualInSealed)
ERRORDEF(550, 0,     ERR_ExplicitPropertyAddingAccessor, IDS_ExplicitPropertyAddingAccessor)
ERRORDEF(551, 0,     ERR_ExplicitPropertyMissingAccessor,IDS_ExplicitPropertyMissingAccessor)
ERRORDEF(552, 0,     ERR_ConversionWithInterface,        IDS_ConversionWithInterface)
ERRORDEF(553, 0,     ERR_ConversionWithBase,             IDS_ConversionWithBase)
ERRORDEF(554, 0,     ERR_ConversionWithDerived,          IDS_ConversionWithDerived)
ERRORDEF(555, 0,     ERR_IdentityConversion,             IDS_IdentityConversion)
ERRORDEF(556, 0,     ERR_ConversionNotInvolvingContainedType, IDS_ConversionNotInvolvingContainedType)
ERRORDEF(557, 0,     ERR_DuplicateConversionInClass,     IDS_DuplicateConversionInClass)
ERRORDEF(558, 0,     ERR_OperatorsMustBeStatic,          IDS_OperatorsMustBeStatic)
ERRORDEF(559, 0,     ERR_BadIncDecSignature,             IDS_BadIncDecSignature)
ERRORDEF(560, 0,     ERR_CantOverrideAccessor,           IDS_CantOverrideAccessor)
ERRORDEF(561, 0,     ERR_CantOverrideSpecialMethod,      IDS_CantOverrideSpecialMethod)
ERRORDEF(562, 0,     ERR_BadUnaryOperatorSignature,      IDS_BadUnaryOperatorSignature)
ERRORDEF(563, 0,     ERR_BadBinaryOperatorSignature,     IDS_BadBinaryOperatorSignature)
//ERRORDEF(564, 0,     ERR_BadShiftOperatorSignature,      IDS_BadShiftOperatorSignature)
//ERRORDEF(565, 0,     ERR_BadEqualsOperatorSignature,     IDS_BadEqualsOperatorSignature)
//ERRORDEF(566, 0,     ERR_BadCompareOperatorSignature,    IDS_BadCompareOperatorSignature)
ERRORDEF(567, 0,     ERR_InterfacesCantContainOperators, IDS_InterfacesCantContainOperators)
ERRORDEF(568, 0,     ERR_StructsCantContainDefaultContructor, IDS_StructsCantContainDefaultContructor)
ERRORDEF(569, 0,     ERR_CantOverrideBogusMethod,        IDS_CantOverrideBogusMethod)
ERRORDEF(570, 0,     ERR_BindToBogus,                    IDS_BindToBogus)
ERRORDEF(571, 0,     ERR_CantCallSpecialMethod,          IDS_CantCallSpecialMethod)
ERRORDEF(572, 0,     ERR_BadTypeReference,               IDS_BadTypeReference)
ERRORDEF(573, 0,     ERR_FieldInitializerInStruct,       IDS_FieldInitializerInStruct)
ERRORDEF(574, 0,     ERR_BadDestructorName,              IDS_BadDestructorName)
ERRORDEF(575, 0,     ERR_OnlyClassesCanContainDestructors,    IDS_OnlyClassesCanContainDestructors)
ERRORDEF(576, 0,     ERR_ConflictAliasAndMember,         IDS_ConflictAliasAndMember)
ERRORDEF(577, 0,     ERR_ConditionalOnSpecialMethod,     IDS_ConditionalOnSpecialMethod)
ERRORDEF(578, 0,     ERR_ConditionalMustReturnVoid,      IDS_ConditionalMustReturnVoid)
ERRORDEF(579, 0,     ERR_DuplicateAttribute,             IDS_DuplicateAttribute)
ERRORDEF(580, 0,     ERR_TooManyArgumentsToAttribute,    IDS_TooManyArgumentsToAttribute)
ERRORDEF(581, 0,     ERR_NamedArgumentToAttribute,       IDS_NamedArgumentToAttribute)
ERRORDEF(582, 0,     ERR_ConditionalOnInterfaceMethod,   IDS_ConditionalOnInterfaceMethod)
ERRORDEF(583, 0,     ERR_ICE_Culprit,                    IDS_ICE_Culprit)
ERRORDEF(584, 0,     ERR_ICE_Symbol,                     IDS_ICE_Symbol)
ERRORDEF(585, 0,     ERR_ICE_Node,                       IDS_ICE_Node)
ERRORDEF(586, 0,     ERR_ICE_File,                       IDS_ICE_File)
ERRORDEF(587, 0,     ERR_ICE_Stage,                      IDS_ICE_Stage)
ERRORDEF(588, 0,     ERR_ICE_Lexer,                      IDS_ICE_Lexer)
ERRORDEF(589, 0,     ERR_ICE_Parser,                     IDS_ICE_Parser)
ERRORDEF(590, 0,     ERR_OperatorCantReturnVoid,         IDS_OperatorCantReturnVoid)
ERRORDEF(591, 0,     ERR_InvalidAttributeArgument,       IDS_InvalidAttributeArgument)
ERRORDEF(592, 0,     ERR_AttributeOnBadSymbolType,       IDS_AttributeOnBadSymbolType)
//ERRORDEF(593, 0,     ERR_DualWithoutUuidAttribute,       IDS_DualWithoutUuidAttribute)
ERRORDEF(594, 0,     ERR_FloatOverflow,                  IDS_FloatOverflow)
//ERRORDEF(595, 0,     ERR_ComImportOnNonEmptyClass,       IDS_ComImportOnNonEmptyClass)
ERRORDEF(596, 0,     ERR_ComImportWithoutUuidAttribute,  IDS_ComImportWithoutUuidAttribute)
ERRORDEF(597, 0,     ERR_TooFewArgumentsToAttribute,     IDS_TooFewArgumentsToAttribute)
//ERRORDEF(598, 0,     ERR_InvalidGuidArgument,            IDS_InvalidGuidArgument)
ERRORDEF(599, 0,     ERR_InvalidNamedArgument,           IDS_InvalidNamedArgument)
//ERRORDEF(600, 0,     ERR_DuplicateAttributeArgument,     IDS_DuplicateAttributeArgument)
ERRORDEF(601, 0,     ERR_DllImportOnInvalidMethod,       IDS_DllImportOnInvalidMethod)
ERRORDEF(602, 1,     WRN_FeatureDeprecated,              IDS_FeatureDeprecated)
//ERRORDEF(603, 0,     ERR_AttributeClassNotPublic,        IDS_AttributeClassNotPublic)
//ERRORDEF(604, 0,     ERR_AttributeClassInNonPublic,      IDS_AttributeClassInNonPublic)
//ERRORDEF(605, 0,     ERR_AttributeConstructorWithBadArgument, IDS_AttributeConstructorWithBadArgument)
//ERRORDEF(606, 0,     ERR_AttributeFieldWithBadType,      IDS_AttributeFieldWithBadType)
//ERRORDEF(607, 0,     ERR_AttributeClassMustHaveConstructor,     IDS_AttributeClassMustHaveConstructor)
//ERRORDEF(608, 0,     ERR_MethodSysNativeAndDllImport,    IDS_MethodSysNativeAndDllImport)
ERRORDEF(609, 0,     ERR_NameAttributeOnOverride,        IDS_NameAttributeOnOverride)
ERRORDEF(610, 0,     ERR_FieldCantBeRefAny,              IDS_FieldCantBeRefAny)
ERRORDEF(611, 0,     ERR_ArrayElementCantBeRefAny,       IDS_ArrayElementCantBeRefAny)
ERRORDEF(612, 1,     WRN_DeprecatedSymbol,               IDS_DeprecatedSymbol)
//ERRORDEF(613, 1,     WRN_InternalAccessBug,              IDS_InternalAccessBug)
//ERRORDEF(614, 0,     ERR_ConversionWithVariant,          IDS_ConversionWithVariant)
//ERRORDEF(615, 0,     ERR_CantOverrideFinal,              IDS_CantOverrideFinal)
ERRORDEF(616, 0,     ERR_NotAnAttributeClass,            IDS_NotAnAttributeClass)
ERRORDEF(617, 0,     ERR_BadNamedAttributeArgument,      IDS_BadNamedAttributeArgument)
ERRORDEF(618, 2,     WRN_DeprecatedSymbolStr,            IDS_DeprecatedSymbolStr)
ERRORDEF(619, 0,     ERR_DeprecatedSymbolStr,            IDS_DeprecatedSymbolStr)  // intentionally the same message as 618
ERRORDEF(620, 0,     ERR_IndexerCantHaveVoidType,        IDS_IndexerCantHaveVoidType)
ERRORDEF(621, 0,     ERR_VirtualPrivate,                 IDS_VirtualPrivate)
ERRORDEF(622, 0,     ERR_ArrayInitToNonArrayType,        IDS_ArrayInitToNonArrayType)
ERRORDEF(623, 0,     ERR_ArrayInitInBadPlace,            IDS_ArrayInitInBadPlace)
//ERRORDEF(624, 0,     ERR_ReturnsHResultOnBadMethod,      IDS_ReturnsHResultOnBadMethod)
ERRORDEF(625, 0,     ERR_MissingStructOffset,            IDS_MissingStructOffset)
ERRORDEF(626, 1,     WRN_ExternMethodNoImplementation,   IDS_ExternMethodNoImplementation)
//ERRORDEF(627, 0,     ERR_SysNativeOnNonExternal,         IDS_SysNativeOnNonExternal)
ERRORDEF(628, 4,     WRN_ProtectedInSealed,              IDS_ProtectedInSealed)
ERRORDEF(629, 0,     ERR_InterfaceImplementedByConditional, IDS_InterfaceImplementedByConditional)
//ERRORDEF(630, 0,     ERR_UnionContainsRef,               IDS_UnionContainsRef)
ERRORDEF(631, 0,     ERR_IndexerWithRefParam,            IDS_IndexerWithRefParam)
ERRORDEF(632, 0,     ERR_NamedAttrArgIsReadOnlyProperty, IDS_NamedAttrArgIsReadOnlyProperty)
ERRORDEF(633, 0,     ERR_BadArgumentToNameAttribute,     IDS_BadArgumentToNameAttribute)
ERRORDEF(634, 0,     ERR_OnlyValidOnCustomMarshaller,    IDS_OnlyValidOnCustomMarshaller)
ERRORDEF(635, 0,     ERR_MissingComTypeOrMarshaller,     IDS_MissingComTypeOrMarshaller)
ERRORDEF(636, 0,     ERR_StructOffsetOnBadStruct,        IDS_StructOffsetOnBadStruct)
ERRORDEF(637, 0,     ERR_StructOffsetOnBadField,         IDS_StructOffsetOnBadField)
//ERRORDEF(638, 0,     ERR_UnknownGlobalAttribute,         IDS_UnknownGlobalAttribute)
//ERRORDEF(639, 0,     ERR_DuplicateGlobalAttribute,       IDS_DuplicateGlobalAttribute)
//ERRORDEF(640, 0,     ERR_AssemblyAttributeOnNonAssembly, IDS_AssemblyAttributeOnNonAssembly)
ERRORDEF(641, 0,     ERR_AttributeUsageOnNonAttributeClass, IDS_AttributeUsageOnNonAttributeClass)
ERRORDEF(642, 3,     WRN_PossibleMistakenNullStatement,  IDS_PossibleMistakenNullStatement)
ERRORDEF(643, 0,     ERR_DuplicateNamedAttributeArgument,IDS_DuplicateNamedAttributeArgument)
ERRORDEF(644, 0,     ERR_DeriveFromEnumOrValueType,      IDS_DeriveFromEnumOrValueType)
ERRORDEF(645, 0,     ERR_IdentifierTooLong,              IDS_IdentifierTooLong)
ERRORDEF(646, 0,     ERR_DefaultMemberOnIndexedType,     IDS_DefaultMemberOnIndexedType)
ERRORDEF(647, 0,     ERR_CustomAttributeError,           IDS_CustomAttributeError)
ERRORDEF(648, 0,     ERR_BogusType,                      IDS_BogusType)
ERRORDEF(649, 4,     WRN_UnassignedInternalField,        IDS_UnassignedInternalField)
ERRORDEF(650, 0,     ERR_CStyleArray,                    IDS_CStyleArray)
ERRORDEF(652, 2,     WRN_VacuousIntegralComp,            IDS_VacuousIntegralComp)
ERRORDEF(653, 0,     ERR_AbstractAttributeClass,         IDS_AbstractAttributeClass)
ERRORDEF(654, 0,     ERR_BadUseOfMethod,                 IDS_BadUseOfMethod)
ERRORDEF(655, 0,     ERR_BadNamedAttributeArgumentType,  IDS_BadNamedAttributeArgumentType)
ERRORDEF(656, 0,     ERR_MissingPredefinedMember,        IDS_MissingPredefinedMember)
ERRORDEF(657, 0,     ERR_AttributeLocationOnBadDeclaration, IDS_AttributeLocationOnBadDeclaration)
ERRORDEF(658, 0,     ERR_InvalidAttributeLocation,       IDS_InvalidAttributeLocation)
ERRORDEF(659, 3,     WRN_EqualsWithoutGetHashCode,       IDS_EqualsWithoutGetHashCode)
ERRORDEF(660, 3,     WRN_EqualityOpWithoutEquals,        IDS_EqualityOpWithoutEquals)
ERRORDEF(661, 3,     WRN_EqualityOpWithoutGetHashCode,   IDS_EqualityOpWithoutGetHashCode)
ERRORDEF(662, 0,     ERR_OutAttrOnRefParam,              IDS_OutAttrOnRefParam)
ERRORDEF(663, 0,     ERR_OverloadRefOut,                 IDS_OverloadRefOut)
ERRORDEF(664, 0,     ERR_LiteralDoubleCast,              IDS_LiteralDoubleCast)
ERRORDEF(665, 3,     WRN_IncorrectBooleanAssg,           IDS_IncorrectBooleanAssg)
ERRORDEF(666, 0,     ERR_ProtectedInStruct,              IDS_ProtectedInStruct)
ERRORDEF(667, 0,     ERR_FeatureDeprecated,              IDS_FeatureDeprecated)
ERRORDEF(668, 0,     ERR_InconsistantIndexerNames,       IDS_InconsistantIndexerNames)
ERRORDEF(669, 0,     ERR_ComImportWithUserCtor,          IDS_ComImportWithUserCtor)
ERRORDEF(670, 0,     ERR_FieldCantHaveVoidType,          IDS_FieldCantHaveVoidType)
//ERRORDEF(671, 2,     WRN_IDisposableAndIEnumerator,      IDS_IDisposableAndIEnumerator)
ERRORDEF(672, 1,     WRN_NonObsoleteOverridingObsolete,  IDS_NonObsoleteOverridingObsolete)
ERRORDEF(673, 0,     ERR_SystemVoid,                     IDS_SystemVoid)
ERRORDEF(674, 0,     ERR_ExplicitParamArray,             IDS_ExplicitParamArray)
ERRORDEF(675, 3,     WRN_BitwiseOrSignExtend,            IDS_BitwiseOrSignExtend)
ERRORDEF(676, 0,     ERR_VolatileByRef,                  IDS_VolatileByRef)
ERRORDEF(677, 0,     ERR_VolatileStruct,                 IDS_VolatileStruct)
ERRORDEF(678, 0,     ERR_VolatileAndReadonly,            IDS_VolatileAndReadonly)
ERRORDEF(679, 1,     WRN_InternalVirtual,                IDS_InternalVirtual)

ERRORDEF(1001, 0,   ERR_IdentifierExpected,             IDS_IdentifierExpected)
ERRORDEF(1002, 0,   ERR_SemicolonExpected,              IDS_SemicolonExpected)
ERRORDEF(1003, 0,   ERR_SyntaxError,                    IDS_SyntaxError)
ERRORDEF(1004, 0,   ERR_DuplicateModifier,              IDS_DuplicateModifier)
ERRORDEF(1005, 0,   ERR_IllegalPointerType,             IDS_IllegalPointerType)
//ERRORDEF(1006, 0,   ERR_BadConstructorName,             IDS_BadConstructorName)   // Not Used
ERRORDEF(1007, 0,   ERR_DuplicateAccessor,              IDS_DuplicateAccessor)
ERRORDEF(1008, 0,   ERR_IntegralTypeExpected,           IDS_IntegralTypeExpected)
ERRORDEF(1009, 0,   ERR_IllegalEscape,                  IDS_IllegalEscape)
ERRORDEF(1010, 0,   ERR_NewlineInConst,                 IDS_NewlineInConst)
ERRORDEF(1011, 0,   ERR_EmptyCharConst,                 IDS_EmptyCharConst)
ERRORDEF(1012, 0,   ERR_TooManyCharsInConst,            IDS_TooManyCharsInConst)
ERRORDEF(1013, 0,   ERR_InvalidNumber,                  IDS_InvalidNumber)
ERRORDEF(1014, 0,   ERR_GetOrSetExpected,               IDS_GetOrSetExpected)
ERRORDEF(1015, 0,   ERR_ClassTypeExpected,              IDS_ClassTypeExpected)
ERRORDEF(1016, 0,   ERR_NamedArgumentExpected,          IDS_NamedArgumentExpected)
ERRORDEF(1017, 0,   ERR_TooManyCatches,                 IDS_TooManyCatches)
ERRORDEF(1018, 0,   ERR_ThisOrBaseExpected,             IDS_ThisOrBaseExpected)
ERRORDEF(1019, 0,   ERR_OvlUnaryOperatorExpected,       IDS_OvlUnaryOperatorExpected)
ERRORDEF(1020, 0,   ERR_OvlBinaryOperatorExpected,      IDS_OvlBinaryOperatorExpected)
ERRORDEF(1021, 0,   ERR_IntOverflow,                    IDS_IntOverflow)
ERRORDEF(1022, 0,   ERR_EOFExpected,                    IDS_EOFExpected)
ERRORDEF(1023, 0,   ERR_BadEmbeddedStmt,                IDS_BadEmbeddedStmt)
ERRORDEF(1024, 0,   ERR_PPDirectiveExpected,            IDS_PPDirectiveExpected)
ERRORDEF(1025, 0,   ERR_EndOfPPLineExpected,            IDS_EndOfPPLineExpected)
ERRORDEF(1026, 0,   ERR_CloseParenExpected,             IDS_CloseParenExpected)
ERRORDEF(1027, 0,   ERR_EndifDirectiveExpected,         IDS_EndifDirectiveExpected)
ERRORDEF(1028, 0,   ERR_UnexpectedDirective,            IDS_UnexpectedDirective)
ERRORDEF(1029, 0,   ERR_ErrorDirective,                 IDS_ErrorDirective)
ERRORDEF(1030, 1,   WRN_WarningDirective,               IDS_WarningDirective)
ERRORDEF(1031, 0,   ERR_TypeExpected,                   IDS_TypeExpected)
ERRORDEF(1032, 0,   ERR_PPDefFollowsToken,              IDS_PPDefFollowsToken)
ERRORDEF(1033, 0,   ERR_TooManyLines,                   IDS_TooManyLines)
ERRORDEF(1034, 0,   ERR_LineTooLong,                    IDS_LineTooLong)
ERRORDEF(1035, 0,   ERR_OpenEndedComment,               IDS_OpenEndedComment)
ERRORDEF(1036, 0,   ERR_ExpectedDotOrParen,             IDS_ExpectedDotOrParen)
ERRORDEF(1037, 0,   ERR_OvlOperatorExpected,            IDS_OvlOperatorExpected)
ERRORDEF(1038, 0,   ERR_EndRegionDirectiveExpected,     IDS_EndRegionDirectiveExpected)
ERRORDEF(1039, 0,   ERR_UnterminatedStringLit,          IDS_UnterminatedStringLit)
ERRORDEF(1040, 0,   ERR_BadDirectivePlacement,          IDS_BadDirectivePlacement)
ERRORDEF(1041, 0,   ERR_IdentifierExpectedKW,           IDS_IdentifierExpectedKW)
//ERRORDEF(1042, 0,   ERR_EscapedKeyword,                 IDS_EscapedKeyword)
ERRORDEF(1043, 0,   ERR_SemiOrLBraceExpected,           IDS_SemiOrLBraceExpected)
ERRORDEF(1044, 0,   ERR_MultiTypeInDeclaration,         IDS_MultiTypeInDeclaration)

ERRORDEF(1055, 0,   ERR_AddOrRemoveExpected,            IDS_AddOrRemoveExpected)

ERRORDEF(1200, 1,   WRN_FeatureDeprecated2,             IDS_FeatureDeprecated)
ERRORDEF(1201, 1,   WRN_FeatureDeprecated3,             IDS_FeatureDeprecated)
ERRORDEF(1202, 1,   WRN_FeatureDeprecated4,             IDS_FeatureDeprecated)
ERRORDEF(1203, 1,   WRN_FeatureDeprecated5,             IDS_FeatureDeprecated)

ERRORDEF(1501, 0,   ERR_BadArgCount,                    IDS_BadArgCount)
ERRORDEF(1502, 0,   ERR_BadArgTypes,                    IDS_BadArgTypes)
ERRORDEF(1503, 0,   ERR_BadArgType,                     IDS_BadArgType)
ERRORDEF(1504, 0,   ERR_NoSourceFile,                   IDS_NoSourceFile)


ERRORDEF(1507, 0,   ERR_CantRefResource,                IDS_CantRefResource)
ERRORDEF(1508, 0,   ERR_ResourceNotUnique,              IDS_ResourceNotUnique)
ERRORDEF(1509, 0,   ERR_ImportNonAssembly,              IDS_ImportNonAssembly)
ERRORDEF(1510, 0,   ERR_RefLvalueExpected,              IDS_RefLvalueExpected)
ERRORDEF(1511, 0,   ERR_BaseInStaticMeth,               IDS_BaseInStaticMeth)
ERRORDEF(1512, 0,   ERR_BaseInBadContext,               IDS_BaseInBadContext)
ERRORDEF(1513, 0,   ERR_RbraceExpected,                 IDS_RbraceExpected)
ERRORDEF(1514, 0,   ERR_LbraceExpected,                 IDS_LbraceExpected)
ERRORDEF(1515, 0,   ERR_InExpected,                     IDS_InExpected)

ERRORDEF(1517, 0,   ERR_InvalidPreprocExpr,             IDS_InvalidPreprocExpr)
ERRORDEF(1518, 0,   ERR_BadTokenInType,                 IDS_BadTokenInType)
ERRORDEF(1519, 0,   ERR_InvalidMemberDecl,              IDS_InvalidMemberDecl)
ERRORDEF(1520, 0,   ERR_MemberNeedsType,                IDS_MemberNeedsType)
ERRORDEF(1521, 0,   ERR_BadBaseType,                    IDS_BadBaseType)
ERRORDEF(1522, 1,   WRN_EmptySwitch,                    IDS_EmptySwitch)
ERRORDEF(1523, 0,   ERR_StmtNotInCase,                  IDS_StmtNotInCase)
ERRORDEF(1524, 0,   ERR_ExpectedEndTry,                 IDS_ExpectedEndTry)
ERRORDEF(1525, 0,   ERR_InvalidExprTerm,                IDS_InvalidExprTerm)
ERRORDEF(1526, 0,   ERR_BadNewExpr,                     IDS_BadNewExpr)
ERRORDEF(1527, 0,   ERR_NoNamespacePrivate,             IDS_NoNamespacePrivate)
ERRORDEF(1528, 0,   ERR_BadVarDecl,                     IDS_BadVarDecl)
ERRORDEF(1529, 0,   ERR_UsingAfterElements,             IDS_UsingAfterElements)
ERRORDEF(1530, 0,   ERR_NoNewOnNamespaceElement,        IDS_NoNewOnNamespaceElement)

//ERRORDEF(1532, 0,   ERR_AccessorMustOverride,           IDS_AccessorMustOverride)
ERRORDEF(1533, 0,   ERR_DontUseInvoke,                  IDS_DontUseInvoke)
ERRORDEF(1534, 0,   ERR_BadBinOpArgs,                   IDS_BadBinOpArgs)
ERRORDEF(1535, 0,   ERR_BadUnOpArgs,                    IDS_BadUnOpArgs)
ERRORDEF(1536, 0,   ERR_NoVoidParameter,                IDS_NoVoidParameter)
ERRORDEF(1537, 0,   ERR_DuplicateAlias,                 IDS_DuplicateAlias)
//ERRORDEF(1538, 0,   ERR_BadTypeReferenceDerived,        IDS_BadTypeReferenceDerived)
//ERRORDEF(1539, 0,   ERR_BadBackQuoteChar,               IDS_BadBackQuoteChar)
ERRORDEF(1540, 0,   ERR_BadProtectedAccess,             IDS_BadProtectedAccess)
ERRORDEF(1541, 0,   ERR_CantIncludeDirectory,           IDS_CantIncludeDirectory)
ERRORDEF(1542, 0,   ERR_AddModuleAssembly,              IDS_AddModuleAssembly)
ERRORDEF(1545, 0,   ERR_BindToBogusProp2,               IDS_BindToBogusProp2)
ERRORDEF(1546, 0,   ERR_BindToBogusProp1,               IDS_BindToBogusProp1)
ERRORDEF(1547, 0,   ERR_NoVoidHere,                     IDS_NoVoidHere)
ERRORDEF(1548, 0,   ERR_CryptoFailed,                   IDS_CryptoFailed)
ERRORDEF(1549, 0,   ERR_CryptoNotFound,                 IDS_CryptoNotFound)

ERRORDEF(1551, 0,   ERR_IndexerNeedsParam,              IDS_IndexerNeedsParam)
ERRORDEF(1552, 0,   ERR_BadArraySyntax,                 IDS_BadArraySyntax)
ERRORDEF(1553, 0,   ERR_BadOperatorSyntax,              IDS_BadOperatorSyntax)
ERRORDEF(1554, 0,   ERR_BadOperatorSyntax2,             IDS_BadOperatorSyntax2)
ERRORDEF(1555, 0,   ERR_MainClassNotFound,              IDS_MainClassNotFound)
ERRORDEF(1556, 0,   ERR_MainClassNotClass,              IDS_MainClassNotClass)
ERRORDEF(1557, 0,   ERR_MainClassWrongFile,             IDS_MainClassWrongFile)
ERRORDEF(1558, 0,   ERR_NoMainInClass,                  IDS_NoMainInClass)
ERRORDEF(1559, 0,   ERR_MainClassIsImport,              IDS_MainClassIsImport)
ERRORDEF(1560, 0,   ERR_FileNameTooLong,                IDS_FileNameTooLong)

ERRORDEF(1562, 0,   ERR_OutputNeedsName,                IDS_OutputNeedsName)
ERRORDEF(1563, 0,   ERR_OutputNeedsInput,               IDS_OutputNeedsInput)
ERRORDEF(1566, 0,   ERR_CantReadResource,               IDS_CantReadResource)
ERRORDEF(1567, 0,   ERR_AutoResGen,                     IDS_AutoResGen)
ERRORDEF(1569, 0,   ERR_DocFileGen,                     IDS_DocFileGen)
ERRORDEF(1570, 1,   WRN_XMLParseError,                  IDS_XMLParseError)
ERRORDEF(1571, 2,   WRN_DuplicateParamTag,              IDS_DuplicateParamTag)
ERRORDEF(1572, 2,   WRN_UnmatchedParamTag,              IDS_UnmatchedParamTag)
ERRORDEF(1573, 4,   WRN_MissingParamTag,                IDS_MissingParamTag)
ERRORDEF(1574, 1,   WRN_BadXMLRef,                      IDS_BadXMLRef)
ERRORDEF(1575, 0,   ERR_BadStackAllocExpr,              IDS_BadStackAllocExpr)
ERRORDEF(1576, 0,   ERR_InvalidLineNumber,              IDS_InvalidLineNumber)
ERRORDEF(1577, 0,   ERR_ALinkFailed,                    IDS_ALinkFailed)
ERRORDEF(1578, 0,   ERR_MissingPPFile,                  IDS_MissingPPFile)
ERRORDEF(1579, 0,   ERR_ForEachMissingMember,           IDS_ForEachMissingMember)
ERRORDEF(1580, 1,   WRN_BadXMLRefParamType,             IDS_BadXMLRefParamType)
ERRORDEF(1581, 1,   WRN_BadXMLRefReturnType,            IDS_BadXMLRefReturnType)
//ERRORDEF(1582, 0,   ERR_ClsWarnAndTrue,                 IDS_ClsWarnAndTrue)
ERRORDEF(1584, 1,   WRN_BadXMLRefSyntax,                IDS_BadXMLRefSyntax)
ERRORDEF(1585, 0,   ERR_BadModifierLocation,            IDS_BadModifierLocation)
ERRORDEF(1586, 0,   ERR_MissingArraySize,               IDS_MissingArraySize)
ERRORDEF(1587, 2,   WRN_UnprocessedXMLComment,          IDS_UnprocessedXMLComment)
ERRORDEF(1588, 0,   ERR_CantGetCORSystemDir,            IDS_CantGetCORSystemDir)
ERRORDEF(1589, 1,   WRN_FailedInclude,                  IDS_FailedInclude)
ERRORDEF(1590, 1,   WRN_InvalidInclude,                 IDS_InvalidInclude)
ERRORDEF(1591, 4,   WRN_MissingXMLComment,              IDS_MissingXMLComment)
ERRORDEF(1592, 1,   WRN_XMLParseIncludeError,           IDS_XMLParseIncludeError)
ERRORDEF(1593, 0,   ERR_BadDelArgCount,                 IDS_BadDelArgCount)
ERRORDEF(1594, 0,   ERR_BadDelArgTypes,                 IDS_BadDelArgTypes)
ERRORDEF(1595, 1,   WRN_MultipleTypeDefs,               IDS_MultipleTypeDefs)
ERRORDEF(1596, 1,   WRN_DocFileGenAndIncr,              IDS_DocFileGenAndIncr)
ERRORDEF(1597, 0,   ERR_UnexpectedSemicolon,            IDS_UnexpectedSemicolon)
ERRORDEF(1598, 1,   WRN_XMLParserNotFound,              IDS_XMLParserNotFound)
ERRORDEF(1599, 0,   ERR_MethodReturnCantBeRefAny,       IDS_MethodReturnCantBeRefAny)
ERRORDEF(1600, 0,   ERR_CompileCancelled,               IDS_CompileCancelled)
ERRORDEF(1601, 0,   ERR_MethodArgCantBeRefAny,          IDS_MethodArgCantBeRefAny)
ERRORDEF(1602, 0,   ERR_MultipleLocalTypeDefs,          IDS_MultipleLocalTypeDefs)
ERRORDEF(1603, 0,   ERR_UnnamedOutputAndIncr,           IDS_UnnamedOutputAndIncr)
ERRORDEF(1604, 0,   ERR_AssgReadonlyLocal,              IDS_AssgReadonlyLocal)
ERRORDEF(1605, 0,   ERR_RefReadonlyLocal,               IDS_RefReadonlyLocal)
ERRORDEF(1606, 0,   ERR_ALinkCloseFailed,               IDS_ALinkCloseFailed)
ERRORDEF(1607, 1,   WRN_ALinkWarn,                      IDS_ALinkWarn)
ERRORDEF(1608, 0,   ERR_CantUseRequiredAttribute,	IDS_CantUseRequiredAttribute)
ERRORDEF(1609, 0,   ERR_NoModifiersOnAccessor,          IDS_NoModifiersOnAccessor)
ERRORDEF(1610, 4,   WRN_DeleteAutoResFailed,            IDS_DeleteAutoResFailed)
ERRORDEF(1611, 0,   ERR_ParamsCantBeRefOut,             IDS_ParamsCantBeRefOut)
ERRORDEF(1612, 0,   ERR_ReturnNotLValue,                IDS_ReturnNotLValue)
ERRORDEF(1613, 0,   ERR_MissingCoClass,                 IDS_MissingCoClass)

ERRORDEF(1900, 0,   ERR_BadWarningLevel,                IDS_BadWarningLevel)
ERRORDEF(1901, 0,   ERR_NoWarningsAsErrors,             IDS_NoWarningsAsErrors)
ERRORDEF(1902, 0,   ERR_BadDebugType,                   IDS_BadDebugType)

ERRORDEF(1903, 0,   ERR_UnknownTestSwitch,              IDS_UnknownTestSwitch)
ERRORDEF(1904, 0,   ERR_BadWarningNumber,               IDS_BadWarningNumber)

// Errors in the range 2000-3000 are reserved for the command-line
ERRORDEF(2000, 0,   ERR_InitError,                      IDS_INITERROR)
ERRORDEF(2001, 0,   ERR_FileNotFound,                   IDS_FILENOTFOUND)
ERRORDEF(2002, 1,   ERR_FileAlreadyIncluded,            IDS_FILEALREADYINCLUDED)
ERRORDEF(2003, 0,   ERR_DuplicateResponseFile,          IDS_DUPLICATERESPONSEFILE)
ERRORDEF(2005, 0,   ERR_NoFileSpec,                     IDS_NOFILESPEC)
ERRORDEF(2006, 0,   ERR_SwitchNeedsString,              IDS_SWITCHNEEDSSTRING)
ERRORDEF(2007, 0,   ERR_BadSwitch,                      IDS_BADSWITCH)
ERRORDEF(2008, 0,   ERR_NoSources,                      IDS_NOSOURCES)
//ERRORDEF(2009, 0,   ERR_BadOptions,                     IDS_BADOPTIONS)
//ERRORDEF(2010, 0,   ERR_CompileFailed,                  IDS_COMPILEFAILED)
ERRORDEF(2011, 0,   ERR_NoResponseFile,                 IDS_NORESPONSEFILE)
ERRORDEF(2012, 0,   ERR_CantOpenFileWrite,              IDS_CANTOPENFILEWRITE)
ERRORDEF(2013, 0,   ERR_BadBaseNumber,                  IDS_BADBASENUMBER)
ERRORDEF(2014, 1,   WRN_UseNewSwitch,                   IDS_USENEWSWITCH)
ERRORDEF(2015, 0,   ERR_BinaryFile,                     IDS_BINARYFILE)
ERRORDEF(2016, 0,   ERR_BadCodepage,                    IDS_BADCODEPAGE)
ERRORDEF(2017, 0,   ERR_NoMainOnDLL,                    IDS_NOMAINONDLL)
ERRORDEF(2018, -1,  FTL_NoMessagesDLL,                  0)     // This one doesn't have a message in the message dll, because it would be moot!
ERRORDEF(2019, -1,   FTL_InvalidTarget,                 IDS_INVALIDTARGET)
ERRORDEF(2020, 0,   ERR_BadTargetForSecondInputSet,     IDS_BADSECONDTARGET)
ERRORDEF(2021, -1,  FTL_InputFileNameTooLong,           IDS_InputFileNameTooLong)
ERRORDEF(2022, 0,   ERR_NoSourcesInLastInputSet,        IDS_NoSourcesInLastInputSet)
ERRORDEF(2023, 1,   WRN_NoConfigNotOnCommandLine,       IDS_NoConfigNotOnCommandLine)
ERRORDEF(2024, 0,   ERR_BadFileAlignment,               IDS_BadFileAlignment)


// NOTE: Range 3000-3999 is reserved for CLS errors.  The compiler does special things
// with these errors, so don't use this range unless it's really a CLS error.
ERRORDEF(3000, 0,   ERR_CLS_NoVarArgs,                  IDS_CLS_NoVarArgs)
ERRORDEF(3001, 0,   ERR_CLS_BadArgType,                 IDS_CLS_BadArgType)
ERRORDEF(3002, 0,   ERR_CLS_BadReturnType,              IDS_CLS_BadReturnType)
ERRORDEF(3003, 0,   ERR_CLS_BadFieldPropType,           IDS_CLS_BadFieldPropType)
ERRORDEF(3004, 0,   ERR_CLS_BadUnicode,                 IDS_CLS_BadUnicode)
ERRORDEF(3005, 0,   ERR_CLS_BadIdentifierCase,          IDS_CLS_BadIdentifierCase)
ERRORDEF(3006, 0,   ERR_CLS_OverloadRefOut,             IDS_CLS_OverloadRefOut)

ERRORDEF(3008, 0,   ERR_CLS_BadIdentifier,              IDS_CLS_BadIdentifier)
ERRORDEF(3009, 0,   ERR_CLS_BadBase,                    IDS_CLS_BadBase)
ERRORDEF(3010, 0,   ERR_CLS_BadInterfaceMember,         IDS_CLS_BadInterfacemember)
ERRORDEF(3011, 0,   ERR_CLS_NoAbstractMembers,          IDS_CLS_NoAbstractMembers)
ERRORDEF(3012, 1,   ERR_WRN_NotOnModules,               IDS_CLS_NotOnModules)
ERRORDEF(3013, 0,   ERR_CLS_ModuleMissingCLS,           IDS_CLS_ModuleMissingCLS)
ERRORDEF(3014, 0,   ERR_CLS_AssemblyNotCLS,             IDS_CLS_AssemblyNotCLS)
ERRORDEF(3015, 0,   ERR_CLS_BadAttributeType,           IDS_CLS_BadAttributeType)
ERRORDEF(3016, 0,   ERR_CLS_ArrayArgumentToAttribute,   IDS_CLS_ArrayArgumentToAttribute)
// END of CLS errors

ERRORDEF(5000, 1,     WRN_UnknownOption,                  IDS_UnknownOption)
ERRORDEF(5001, 0,     ERR_NoEntryPoint,                   IDS_NoEntryPoint)


