// ==++==
//
//   
//    Copyright (c) 2002 Microsoft Corporation.  All rights reserved.
//   
//    The use and distribution terms for this software are contained in the file
//    named license.txt, which can be found in the root of this distribution.
//    By using this software in any fashion, you are agreeing to be bound by the
//    terms of this license.
//   
//    You must not remove this notice, or any other, from this software.
//   
//
// ==--==
// ===========================================================================
// File: msgsids.h
//
// ===========================================================================
//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by csharp\sccomp\msgs.rc
//
#define IDS_InternalError               1
#define IDS_NoMemory                    3
#define IDS_WarningAsError              4
#define IDS_MissingOptionArg            5
#define IDS_NoMetadataFile              6
#define IDS_ComPlusInit                 7
#define IDS_MetadataImportFailure       8
#define IDS_MetadataCantOpenFile        9
#define IDS_NamespaceTypeConflict       10
#define IDS_CantImportBase              11
#define IDS_NoTypeDef                   12
#define IDS_MetadataEmitFailure         13
#define IDS_RequiredFileNotFound        14
#define IDS_ClassNameTooLong            15
#define IDS_OutputWriteFailed           16
#define IDS_MultipleEntryPoints         17
#define IDS_UnimplementedOp             18
#define IDS_BadBinaryOps                19
#define IDS_IntDivByZero                20
#define IDS_BadIndexLHS                 21
#define IDS_BadIndexCount               22
#define IDS_BadUnaryOp                  23
#define IDS_NoStdLib                    25
#define IDS_ThisInStaticMeth            26
#define IDS_ThisInBadContext            27
#define IDS_InvalidMainSig              28
#define IDS_NoImplicitConv              29
#define IDS_NoExplicitConv              30
#define IDS_ConstOutOfRange             31
#define IDS_IncBuildWrite               32
#define IDS_IncBuildWriteIO             33
#define IDS_AmbigBinaryOps              34
#define IDS_AmbigUnaryOp                35
#define IDS_InAttrOnOutParam            36
#define IDS_ValueCantBeNull             37
#define IDS_WrongNestedThis             38
#define IDS_NoExplicitBuiltinConv       39
#define IDS_DebugInit                   40
#define IDS_DebugEmitFailure            41
#define IDS_DebugInitFile               42
#define IDS_BadPDBFormat                43
#define IDS_BadVisReturnType            50
#define IDS_BadVisParamType             51
#define IDS_BadVisFieldType             52
#define IDS_BadVisPropertyType          53
#define IDS_BadVisIndexerReturn         54
#define IDS_BadVisIndexerParam          55
#define IDS_BadVisOpReturn              56
#define IDS_BadVisOpParam               57
#define IDS_BadVisDelegateReturn        58
#define IDS_BadVisDelegateParam         59
#define IDS_BadVisBaseClass             60
#define IDS_BadVisBaseInterface         61
#define IDS_EventNeedsBothAccessors     65
#define IDS_EventNotDelegate            66
#define IDS_UnreferencedEvent           67
#define IDS_InterfaceEventInitializer   68
#define IDS_EventPropertyInInterface    69
#define IDS_BadEventUsage               70
#define IDS_ExplicitEventFieldImpl      71
#define IDS_CantOverrideNonEvent        72
#define IDS_AddRemoveMustHaveBody       73
#define IDS_AbstractEventInitializer    74
#define IDS_PossibleBadNegCast          75
#define IDS_ReservedEnumerator          76
#define IDS_AsMustHaveReferenceType     77
#define IDS_LowercaseEllSuffix          78
#define IDS_BadEventUsage2              79
#define IDS_BadEventUsageNoField        79
#define IDS_DuplicateParamName          100
#define IDS_DuplicateNameInNS           101
#define IDS_DuplicateNameInClass        102
#define IDS_NameNotInContext            103
#define IDS_AmbigContext                104
#define IDS_DuplicateUsing              105
#define IDS_BadMemberFlag               106
#define IDS_BadMemberProtection         107
#define IDS_NewRequired                 108
#define IDS_NewNotRequired              109
#define IDS_CircConstValue              110
#define IDS_MemberAlreadyExists         111
#define IDS_StaticNotVirtual            112
#define IDS_OverrideNotNew              113
#define IDS_NewOrOverrideExpected       114
#define IDS_OverrideNotExpected         115
#define IDS_NamespaceUnexpected         116
#define IDS_NoSuchMember                117
#define IDS_BadSKknown                  118
#define IDS_BadSKunknown                119
#define IDS_ObjectRequired              120
#define IDS_AmbigCall                   121
#define IDS_BadAccess                   122
#define IDS_InvalidCall                 123
#define IDS_RetObjectRequired           126
#define IDS_RetNoObjectRequired         127
#define IDS_LocalDuplicate              128
#define IDS_AssgLvalueExpected          131
#define IDS_StaticConstParam            132
#define IDS_NotConstantExpression       133
#define IDS_IllegalQualifiedNamespace   134
#define IDS_NameIllegallyOverrides      135
#define IDS_LocalIllegalyOverrides      136
#define IDS_LocalIllegallyOverrides     136
#define IDS_BadUsingNamespace           138
#define IDS_NoBreakOrCont               139
#define IDS_DuplicateLabel              140
#define IDS_FeatureNYI                  141
#define IDS_NoConstructors              143
#define IDS_NoNewAbstract               144
#define IDS_ConstValueRequired          145
#define IDS_CircularBase                146
#define IDS_BadDelegateConstructor      148
#define IDS_MethodNameExpected          149
#define IDS_ConstantExpected            150
#define IDS_IntegralTypeValueExpected   151
#define IDS_DuplicateCaseLabel          152
#define IDS_InvalidGotoCase             153
#define IDS_PropertyLacksGet            154
#define IDS_BadExceptionType            155
#define IDS_BadEmptyThrow               156
#define IDS_BadFinallyLeave             157
#define IDS_LabelShadow                 158
#define IDS_LabelNotFound               159
#define IDS_UnreachableCatch            160
#define IDS_ReturnExpected              161
#define IDS_UnreachableCode             162
#define IDS_SwitchFallThrough           163
#define IDS_UnreferencedLabel           164
#define IDS_UseDefViolation             165
#define IDS_SwitchFallInto              166
#define IDS_NoInvoke                    167
#define IDS_UnreferencedVar             168
#define IDS_UnreferencedField           169
#define IDS_UseDefViolationField        170
#define IDS_UnassignedThis              171
#define IDS_AmbigQM                     172
#define IDS_InvalidQM                   173
#define IDS_NoBaseClass                 174
#define IDS_BaseIllegal                 175
#define IDS_ObjectProhibited            176
#define IDS_ParamUnassigned             177
#define IDS_InvalidArray                178
#define IDS_ExternHasBody               179
#define IDS_AbstractAndExtern           180
#define IDS_UnknownAttribute            181
#define IDS_BadAttributeParam           182
#define IDS_IsAlwaysTrue                183
#define IDS_IsAlwaysFalse               184
#define IDS_LockNeedsReference          185
#define IDS_NullNotValid                186
#define IDS_NoSuchOperator              187
#define IDS_UseDefViolationThis         188
#define IDS_FeatureNYI2                 189
#define IDS_ArgsInvalid                 190
#define IDS_AssgReadonly                191
#define IDS_RefReadonly                 192
#define IDS_PtrExpected                 193
#define IDS_IllegalArrow                194
#define IDS_ArrowNoBase                 195
#define IDS_PtrIndexSingle              196
#define IDS_ByRefNonAgileField          197
#define IDS_AssgReadonlyStatic          198
#define IDS_RefReadonlyStatic           199
#define IDS_AssgReadonlyProp            200
#define IDS_IllegalStatement            201
#define IDS_BadGetEnumerator            202
#define IDS_BadMethodObject             203
#define IDS_TooManyLocals               204
#define IDS_AbstractBaseCall            205
#define IDS_RefProperty                 206
#define IDS_ManagedAddr                 208
#define IDS_BadFixedInitType            209
#define IDS_FixedMustInit               210
#define IDS_InvalidAddrOp               211
#define IDS_FixedNeeded                 212
#define IDS_FixedNotNeeded              213
#define IDS_UnsafeNeeded                214
#define IDS_OpTFRetType                 215
#define IDS_OperatorNeedsMatch          216
#define IDS_BadBoolOp                   217
#define IDS_MustHaveOpTF                218
#define IDS_UnreferencedVarAssg         219
#define IDS_CheckedOverflow             220
#define IDS_ConstOutOfRangeChecked      221
#define IDS_UnknownRankAddress          222
#define IDS_NoNullCase                  223
#define IDS_VarargsAndParams            224
#define IDS_ParamsMustBeArray           225
#define IDS_IllegalArglist              226
#define IDS_IllegalUnsafe               227
#define IDS_NoAccessibleMember          228
#define IDS_AmbigMethProp               229
#define IDS_BadForeachDecl              230
#define IDS_ParamsVarargsLast           231
#define IDS_AmbigArrayIndex             232
#define IDS_SizeofUnsafe                233
#define IDS_TypeNameNotFound            234
#define IDS_VarargDelegate              235
#define IDS_FieldInitRefNonstatic       236
#define IDS_VarargIndexer               237
#define IDS_SealedNonOverride           238
#define IDS_CantOverrideSealed          239
#define IDS_MemberAbstractSealed        240
#define IDS_NoDefaultArgs               241
#define IDS_VoidError                   242
#define IDS_ConditionalOnOverride       243
#define IDS_PointerInAsOrIs             244
#define IDS_CallingFinalizeDepracated   245
#define IDS_SingleTypeNameNotFound      246
#define IDS_NegativeStackAllocSize      247
#define IDS_NegativeArraySize           248
#define IDS_OverrideFinalizeDepracated  249
#define IDS_CallingBaseFinalizeDeprecated 250
#define IDS_NegativeArrayIndex          251
#define IDS_BadRefCompareLeft           252
#define IDS_BadRefCompareRight          253
#define IDS_BadCastInFixed              254
#define IDS_StackallocInCatchFinally    255
#define IDS_MalformedString             256
#define IDS_AbstractHasBody             500
#define IDS_ConcreteMissingBody         501
#define IDS_AbstractAndSealed           502
#define IDS_AbstractNotVirtual          503
#define IDS_StaticConstant              504
#define IDS_CantOverrideNonFunction     505
#define IDS_CantOverrideNonVirtual      506
#define IDS_CantChangeAccessOnOverride  507
#define IDS_CantChangeReturnTypeOnOverride 508
#define IDS_CantDeriveFromSealedClass   509
#define IDS_AbstractInConcreteClass     513
#define IDS_StaticConstructorWithExplicitConstructorCall 514
#define IDS_StaticConstructorWithAccessModifiers 515
#define IDS_RecursiveConstructorCall    516
#define IDS_ObjectCallingBaseConstructor 517
#define IDS_PredefinedTypeNotFound      518
#define IDS_PredefinedTypeBadNamespace  519
#define IDS_PredefinedTypeBadType       520
#define IDS_StructWithBaseConstructorCall 522
#define IDS_StructLayoutCycle           523
#define IDS_InterfacesCannotContainTypes 524
#define IDS_InterfacesCantContainFields 525
#define IDS_InterfacesCantContainConstructors 526
#define IDS_NonInterfaceInInterfaceList 527
#define IDS_DuplicateInterfaceInBaseList 528
#define IDS_CycleInInterfaceInheritance 529
#define IDS_InterfaceMemberHasBody      531
#define IDS_HidingAbstractMethod        533
#define IDS_UnimplementedAbstractMethod 534
#define IDS_UnimplementedInterfaceMember 535
#define IDS_CloseUnimplementedInterfaceMember 536
#define IDS_ObjectCantHaveBases         537
#define IDS_ExplicitInterfaceImplementationNotInterface 538
#define IDS_InterfaceMemberNotFound     539
#define IDS_ClassDoesntImplementInterface 540
#define IDS_ExplicitInterfaceImplementationInNonClassOrStruct 541
#define IDS_MemberNameSameAsType        542
#define IDS_EnumeratorOverflow          543
#define IDS_CantOverrideNonProperty     544
#define IDS_NoGetToOverride             545
#define IDS_NoSetToOverride             546
#define IDS_PropertyCantHaveVoidType    547
#define IDS_PropertyWithNoAccessors     548
#define IDS_NewVirtualInSealed          549
#define IDS_ExplicitPropertyAddingAccessor 550
#define IDS_ExplicitPropertyMissingAccessor 551
#define IDS_ConversionWithInterface     552
#define IDS_ConversionWithBase          553
#define IDS_ConversionWithDerived       554
#define IDS_IdentityConversion          555
#define IDS_ConversionNotInvolvingContainedType 556
#define IDS_DuplicateConversionInClass  557
#define IDS_OperatorsMustBeStatic       558
#define IDS_BadIncDecSignature          559
#define IDS_CantOverrideAccessor        560
#define IDS_CantOverrideSpecialMethod   561
#define IDS_BadUnaryOperatorSignature   562
#define IDS_BadBinaryOperatorSignature  563
#define IDS_BadShiftOperatorSignature   564
#define IDS_BadEqualsOperatorSignature  565
#define IDS_BadCompareOperatorSignature 566
#define IDS_InterfacesCantContainOperators 567
#define IDS_StructsCantContainDefaultContructor 568
#define IDS_CantOverrideBogusMethod     569
#define IDS_BindToBogus                 570
#define IDS_CantCallSpecialMethod       571
#define IDS_BadTypeReference            572
#define IDS_FieldInitializerInStruct    573
#define IDS_BadDestructorName           574
#define IDS_OnlyClassesCanContainDestructors 575
#define IDS_ConflictAliasAndMember      576
#define IDS_ConditionalOnSpecialMethod  577
#define IDS_ConditionalMustReturnVoid   578
#define IDS_DuplicateAttribute          579
#define IDS_TooManyArgumentsToAttribute 580
#define IDS_NamedArgumentToAttribute    581
#define IDS_ConditionalOnInterfaceMethod 582
#define IDS_ICE_Culprit                 583
#define IDS_ICE_Symbol                  584
#define IDS_ICE_Node                    585
#define IDS_ICE_File                    586
#define IDS_ICE_Stage                   587
#define IDS_ICE_Lexer                   588
#define IDS_ICE_Parser                  589
#define IDS_OperatorCantReturnVoid      590
#define IDS_InvalidAttributeArgument    591
#define IDS_AttributeOnBadSymbolType    592
#define IDS_FloatOverflow               594
#define IDS_ComImportWithoutUuidAttribute 596
#define IDS_TooFewArgumentsToAttribute  597
#define IDS_InvalidNamedArgument        599
#define IDS_DllImportOnInvalidMethod    601
#define IDS_FeatureDeprecated           602
#define IDS_NameAttributeOnOverride     609
#define IDS_FieldCantBeRefAny           610
#define IDS_ArrayElementCantBeRefAny    611
#define IDS_DeprecatedSymbol            612
#define IDS_CantOverrideFinal           615
#define IDS_NotAnAttributeClass         616
#define IDS_BadNamedAttributeArgument   617
#define IDS_DeprecatedSymbolStr         618
#define IDS_IndexerCantHaveVoidType     620
#define IDS_VirtualPrivate              621
#define IDS_ArrayInitToNonArrayType     622
#define IDS_ArrayInitInBadPlace         623
#define IDS_MissingStructOffset         625
#define IDS_ExternMethodNoImplementation 626
#define IDS_ProtectedInSealed           628
#define IDS_InterfaceImplementedByConditional 629
#define IDS_IndexerWithRefParam         631
#define IDS_NamedAttrArgIsReadOnlyProperty 632
#define IDS_BadArgumentToNameAttribute  633
#define IDS_OnlyValidOnCustomMarshaller 634
#define IDS_MissingComTypeOrMarshaller  635
#define IDS_StructOffsetOnBadStruct     636
#define IDS_StructOffsetOnBadField      637
#define IDS_AttributeUsageOnNonAttributeClass 641
#define IDS_PossibleMistakenNullStatement 642
#define IDS_DuplicateNamedAttributeArgument 643
#define IDS_DeriveFromEnumOrValueType   644
#define IDS_IdentifierTooLong           645
#define IDS_DefaultMemberOnIndexedType  646
#define IDS_CustomAttributeError        647
#define IDS_BogusType                   648
#define IDS_UnassignedInternalField     649
#define IDS_CStyleArray                 650
#define IDS_GlobalAttributeInWrongScope 651
#define IDS_VacuousIntegralComp         652
#define IDS_AbstractAttributeClass      653
#define IDS_BadUseOfMethod              654
#define IDS_BadNamedAttributeArgumentType 655
#define IDS_MissingPredefinedMember     656
#define IDS_AttributeLocationOnBadDeclaration 657
#define IDS_InvalidAttributeLocation    658
#define IDS_EqualsWithoutGetHashCode    659
#define IDS_EqualityOpWithoutEquals     660
#define IDS_EqualityOpWithoutGetHashCode 661
#define IDS_OutAttrOnRefParam           662
#define IDS_OverloadRefOut              663
#define IDS_LiteralDoubleCast           664
#define IDS_IncorrectBooleanAssg        665
#define IDS_ProtectedInStruct           666
#define IDS_InconsistantIndexerNames    668
#define IDS_ComImportWithUserCtor       669
#define IDS_FieldCantHaveVoidType       670
#define IDS_NonObsoleteOverridingObsolete 672
#define IDS_SystemVoid                  673
#define IDS_ExplicitParamArray          674
#define IDS_BitwiseOrSignExtend         675
#define IDS_VolatileByRef               676
#define IDS_VolatileStruct              677
#define IDS_VolatileAndReadonly         678
#define IDS_InternalVirtual             679
#define IDS_IdentifierExpected          1001
#define IDS_SemicolonExpected           1002
#define IDS_SyntaxError                 1003
#define IDS_DuplicateModifier           1004
#define IDS_IllegalPointerType          1005
#define IDS_DuplicateAccessor           1007
#define IDS_IntegralTypeExpected        1008
#define IDS_IllegalEscape               1009
#define IDS_NewlineInConst              1010
#define IDS_EmptyCharConst              1011
#define IDS_TooManyCharsInConst         1012
#define IDS_InvalidNumber               1013
#define IDS_GetOrSetExpected            1014
#define IDS_ClassTypeExpected           1015
#define IDS_NamedArgumentExpected       1016
#define IDS_TooManyCatches              1017
#define IDS_ThisOrBaseExpected          1018
#define IDS_OvlUnaryOperatorExpected    1019
#define IDS_OvlBinaryOperatorExpected   1020
#define IDS_IntOverflow                 1021
#define IDS_EOFExpected                 1022
#define IDS_BadEmbeddedStmt             1023
#define IDS_PPDirectiveExpected         1024
#define IDS_EndOfPPLineExpected         1025
#define IDS_CloseParenExpected          1026
#define IDS_EndifDirectiveExpected      1027
#define IDS_UnexpectedDirective         1028
#define IDS_ErrorDirective              1029
#define IDS_WarningDirective            1030
#define IDS_TypeExpected                1031
#define IDS_PPDefFollowsToken           1032
#define IDS_TooManyLines                1033
#define IDS_LineTooLong                 1034
#define IDS_OpenEndedComment            1035
#define IDS_ExpectedDotOrParen          1036
#define IDS_OvlOperatorExpected         1037
#define IDS_EndRegionDirectiveExpected  1038
#define IDS_UnterminatedStringLit       1039
#define IDS_BadDirectivePlacement       1040
#define IDS_IdentifierExpectedKW        1041
#define IDS_EscapedKeyword              1042
#define IDS_SemiOrLBraceExpected        1043
#define IDS_MultiTypeInDeclaration      1044
#define IDS_AddOrRemoveExpected         1055
#define IDS_BadArgCount                 1501
#define IDS_BadArgTypes                 1502
#define IDS_BadArgType                  1503
#define IDS_NoSourceFile                1504
#define IDS_CantRefResource             1507
#define IDS_ResourceNotUnique           1508
#define IDS_ImportNonAssembly           1509
#define IDS_RefLvalueExpected           1510
#define IDS_BaseInStaticMeth            1511
#define IDS_BaseInBadContext            1512
#define IDS_RbraceExpected              1513
#define IDS_LbraceExpected              1514
#define IDS_InExpected                  1515
#define IDS_InvalidPreprocExpr          1517
#define IDS_BadTokenInType              1518
#define IDS_InvalidMemberDecl           1519
#define IDS_MemberNeedsType             1520
#define IDS_BadBaseType                 1521
#define IDS_EmptySwitch                 1522
#define IDS_StmtNotInCase               1523
#define IDS_ExpectedEndTry              1524
#define IDS_InvalidExprTerm             1525
#define IDS_BadNewExpr                  1526
#define IDS_NoNamespacePrivate          1527
#define IDS_BadVarDecl                  1528
#define IDS_UsingAfterElements          1529
#define IDS_NoNewOnNamespaceElement     1530
#define IDS_NoNewOrUnsafeOnNamespaceElement 1530
#define IDS_BadDelegateNew              1531
#define IDS_DontUseInvoke               1533
#define IDS_BadBinOpArgs                1534
#define IDS_BadUnOpArgs                 1535
#define IDS_NoVoidParameter             1536
#define IDS_DuplicateAlias              1537
#define IDS_BadBackQuoteChar            1539
#define IDS_BadProtectedAccess          1540
#define IDS_CantIncludeDirectory        1541
#define IDS_AddModuleAssembly           1542
#define IDS_ModuleNotScoped             1543
#define IDS_ModuleNotAdded              1544
#define IDS_BindToBogusProp2            1545
#define IDS_BindToBogusProp1            1546
#define IDS_NoVoidHere                  1547
#define IDS_CryptoFailed                1548
#define IDS_CryptoNotFound              1549
#define IDS_IndexerNeedsParam           1551
#define IDS_BadArraySyntax              1552
#define IDS_BadOperatorSyntax           1553
#define IDS_BadOperatorSyntax2          1554
#define IDS_MainClassNotFound           1555
#define IDS_MainClassNotClass           1556
#define IDS_MainClassWrongFile          1557
#define IDS_NoMainInClass               1558
#define IDS_MainClassIsImport           1559
#define IDS_FileNameTooLong             1560
#define IDS_OutputNeedsName             1562
#define IDS_OutputNeedsInput            1563
#define IDS_MethodReturnCantBeRefAny    1564
#define IDS_CantReadResource            1566
#define IDS_AutoResGen                  1567
#define IDS_CantReadIcon                1568
#define IDS_DocFileGen                  1569
#define IDS_XMLParseError               1570
#define IDS_DuplicateParamTag           1571
#define IDS_UnmatchedParamTag           1572
#define IDS_MissingParamTag             1573
#define IDS_BadXMLRef                   1574
#define IDS_BadStackAllocExpr           1575
#define IDS_InvalidLineNumber           1576
#define IDS_ALinkFailed                 1577
#define IDS_MissingPPFile               1578
#define IDS_ForEachMissingMember        1579
#define IDS_BadXMLRefParamType          1580
#define IDS_BadXMLRefReturnType         1581
#define IDS_ClsWarnAndTrue              1582
#define IDS_BadXMLRefSyntax             1584
#define IDS_BadModifierLocation         1585
#define IDS_MissingArraySize            1586
#define IDS_InvalidParamsLocation       1587
#define IDS_UnprocessedXMLComment       1588
#define IDS_CantGetCORSystemDir         1589
#define IDS_FailedInclude               1590
#define IDS_InvalidInclude              1591
#define IDS_MissingXMLComment           1592
#define IDS_XMLParseIncludeError        1593
#define IDS_BadDelArgCount              1594
#define IDS_BadDelArgTypes              1595
#define IDS_MultipleTypeDefs            1596
#define IDS_DocFileGenAndIncr           1597
#define IDS_XMLParserNotFound           1598
#define IDS_UnexpectedSemicolon         1599
#define IDS_CompileCancelled            1600
#define IDS_MethodArgCantBeRefAny       1601
#define IDS_MultipleLocalTypeDefs       1602
#define IDS_UnnamedOutputAndIncr        1603
#define IDS_AssgReadonlyLocal           1604
#define IDS_RefReadonlyLocal            1605
#define IDS_ALinkCloseFailed            1606
#define IDS_ALinkWarn                   1607
#define IDS_CantUseRequiredAttribute    1608
#define IDS_NoModifiersOnAccessor       1609
#define IDS_DeleteAutoResFailed         1610
#define IDS_ParamsCantBeRefOut          1611
#define IDS_ReturnNotLValue             1612
#define IDS_MissingCoClass              1613
#define IDS_BadWarningLevel             1900
#define IDS_NoWarningsAsErrors          1901
#define IDS_BadDebugType                1902
#define IDS_UnknownTestSwitch           1903
#define IDS_BadWarningNumber            1904
#define IDS_SK_METHOD                   2000
#define IDS_SK_CLASS                    2001
#define IDS_SK_NAMESPACE                2002
#define IDS_SK_FIELD                    2003
#define IDS_SK_PROPERTY                 2004
#define IDS_SK_UNKNOWN                  2005
#define IDS_SK_VAIRABLE                 2006
#define IDS_SK_EVENT                    2007
#define IDS_CHILD                       2100
#define IDS_PARENT                      2101
#define IDS_CLS_NoVarArgs               3000
#define IDS_CLS_BadArgType              3001
#define IDS_CLS_BadReturnType           3002
#define IDS_CLS_BadFieldPropType        3003
#define IDS_CLS_BadUnicode              3004
#define IDS_CLS_BadIdentifierCase       3005
#define IDS_CLS_OverloadRefOut          3006
#define IDS_CLS_BadIdentifier           3008
#define IDS_CLS_BadBase                 3009
#define IDS_CLS_BadInterfacemember      3010
#define IDS_CLS_NoAbstractMembers       3011
#define IDS_CLS_NotOnModules            3012
#define IDS_CLS_ModuleMissingCLS        3013
#define IDS_CLS_AssemblyNotCLS          3014
#define IDS_CLS_BadAttributeType        3015
#define IDS_CLS_ArrayArgumentToAttribute 3016
#define IDS_CLB_ERROR_FIRST             4000
#define IDS_STRING4001                  4001
#define IDS_STRING4002                  4003
#define IDS_STRING4003                  4005
#define IDS_STRING4004                  4006
#define IDS_STRING4005                  4007
#define IDS_STRING4006                  4008
#define IDS_STRING4007                  4010
#define IDS_STRING4011                  4011
#define IDS_STRING4012                  4012
#define IDS_STRING4013                  4013
#define IDS_STRING4014                  4014
#define IDS_STRING4015                  4015
#define IDS_STRING4016                  4016
#define IDS_UnknownOption               5000
#define IDS_NoEntryPoint                5001
#define IDS_TestError                   6666
#define IDS_TestWarn1                   6667
#define IDS_TestWarn2                   6668
#define IDS_TestWarn3                   6669
#define IDS_TestError3                  6670
#define IDS_OD_WARNINGLEVEL             8000
#define IDS_OD_WARNINGSAREERRORS        8001
#define IDS_OD_CCSYMBOLS                8002
#define IDS_OD_NOSTDLIB                 8003
#define IDS_OD_EMITDEBUGINFO            8004
#define IDS_OD_OPTIMIZATIONS            8005
#define IDS_OD_IMPORTS                  8006
#define IDS_OD_NOCODEGEN                8012
#define IDS_OD_TIMING                   8013
#define IDS_OD_CLS                      8014
#define IDS_OD_INCBUILD                 8015
#define IDS_OD_MODULES                  8016
#define IDS_OD_NOWARNLIST               8018
#define IDS_OD_XML_DOCFILE              8023
#define IDS_OD_CHECKED                  8024
#define IDS_OD_UNSAFE                   8025
#define IDS_OD_HIDDEN                   8999
#define IDS_ERRORSYM                    10000
#define IDS_NULL                        10001
#define IDS_RELATEDERROR                10002
#define IDS_RELATEDWARNING              10003
#define IDS_XMLIGNORED                  10004
#define IDS_XMLIGNORED2                 10005
#define IDS_XMLFAILEDINCLUDE            10006
#define IDS_XMLBADINCLUDE               10007
#define IDS_XMLNOINCLUDE                10008
#define IDS_XMLMISSINGINCLUDEFILE       10009
#define IDS_XMLMISSINGINCLUDEPATH       10010
#define IDR_FACTORYRGS                  11000
#define IDS_INITERROR                   12004
#define IDS_FILENOTFOUND                12005
#define IDS_NORESPONSEFILE              12007
#define IDS_NOFILESPEC                  12008
#define IDS_BADSWITCH                   12009
#define IDS_NOSOURCES                   12011
#define IDS_SWITCHNEEDSSTRING           12013
#define IDS_DUPLICATERESPONSEFILE       12014
#define IDS_FILEALREADYINCLUDED         12015
#define IDS_CANTOPENFILEWRITE           12017
#define IDS_BADBASENUMBER               12018
#define IDS_USENEWSWITCH                12019
#define IDS_BINARYFILE                  12020
#define IDS_BADCODEPAGE                 12021
#define IDS_NOMAINONDLL                 12022
#define IDS_NOMESSAGESDLL               12023
#define IDS_INVALIDTARGET               12023
#define IDS_BADSECONDTARGET             12024
#define IDS_InputFileNameTooLong        12025
#define IDS_NoSourcesInLastInputSet     12026
#define IDS_NoConfigNotOnCommandLine    12027
#define IDS_BadFileAlignment            12028
#define IDS_BANNER1                     12101
#define IDS_BANNER1PART2                12102
#define IDS_BANNER2                     12103
#define IDS_VERSION_CONFLICT            12150
#define IDS_HELP10                      12210
#define IDS_SHORTFORM                   12211
#define IDS_OD_TMOD                     12212
#define IDS_OD_TEXE                     12213
#define IDS_OD_TWIN                     12214
#define IDS_OD_TDLL                     12215
#define IDS_OD_OUT                      12216
#define IDS_OD_WINRES                   12217
#define IDS_OD_WINICON                  12218
#define IDS_OD_EMBED                    12219
#define IDS_OD_LINK                     12220
#define IDS_OD_RESPONSE                 12221
#define IDS_OD_RECURSE                  12222
#define IDS_OD_HELP                     12223
#define IDS_OD_NOLOGO                   12224
#define IDS_OD_BUG                      12225
#define IDS_OD_CODEPAGE                 12226
#define IDS_OD_MAIN                     12227
#define IDS_OD_BASE                     12228
#define IDS_OD_FULLPATH                 12229
#define IDS_OD_DEBUGTYPE                12230
#define IDS_OD_NOCONFIG                 12231
#define IDS_OD_LIBPATH                  12232
#define IDS_OD_ALIGN                    12233
#define IDS_OD_UTF8OUT                  12234
#define IDS_REPROTITLE                  12300
#define IDS_REPROVER                    12301
#define IDS_REPROOS                     12302
#define IDS_REPROUSER                   12303
#define IDS_REPROCOMMANDLINE            12304
#define IDS_REPROSOURCEFILE             12305
#define IDS_REPRODIAGS                  12306
#define IDS_REPROISSUETYPE              12307
#define IDS_REPRODESCRIPTION            12308
#define IDS_REPROCORRECTBEHAVIOR        12309
#define IDS_REPROURTVER                 12310
#define IDS_REPROBINFILE                12311
#define IDS_BUGREPORT1                  12340
#define IDS_BUGREPORT2                  12341
#define IDS_BUGREPORT3                  12342
#define IDS_ENTERDESC                   12350
#define IDS_ENTERCORRECT                12351
#define IDS_OD_GRP_OUTPUT               12400
#define IDS_OD_GRP_INPUT                12401
#define IDS_OD_GRP_RES                  12402
#define IDS_OD_GRP_CODE                 12403
#define IDS_OD_GRP_ERRORS               12404
#define IDS_OD_GRP_LANGUAGE             12405
#define IDS_OD_GRP_MISC                 12406
#define IDS_OD_GRP_ADVANCED             12407
#define IDS_OD_ARG_FILELIST             12450
#define IDS_OD_ARG_FILE                 12451
#define IDS_OD_ARG_SYMLIST              12452
#define IDS_OD_ARG_WILDCARD             12453
#define IDS_OD_ARG_TYPE                 12454
#define IDS_OD_ARG_RESINFO              12455
#define IDS_OD_ARG_WARNLSIT             12456
#define IDS_OD_ARG_ADDR                 12457
#define IDS_OD_ARG_NUMBER               12458
#define IDS_OD_ARG_DEBUGTYPE            12459

// Next default values for new objects
// 
