// ==++==
// 
//   
//    Copyright (c) 2002 Microsoft Corporation.  All rights reserved.
//   
//    The use and distribution terms for this software are contained in the file
//    named license.txt, which can be found in the root of this distribution.
//    By using this software in any fashion, you are agreeing to be bound by the
//    terms of this license.
//   
//    You must not remove this notice, or any other, from this software.
//   
// 
// ==--==
/*============================================================
**
**Class: FlowControl
**
**Purpose: Exposes FlowControl Attribute of IL .
**
** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT BY HAND!
** See clr\src\inc\opcodegen.pl for more information.**
============================================================*/
namespace System.Reflection.Emit {

using System;

/// <include file='doc\FlowControl.uex' path='docs/doc[@for="FlowControl"]/*' />
[Serializable]
public enum FlowControl
{

	/// <include file='doc\FlowControl.uex' path='docs/doc[@for="FlowControl.Branch"]/*' />
	Branch	= 0,
	/// <include file='doc\FlowControl.uex' path='docs/doc[@for="FlowControl.Break"]/*' />
	Break	= 1,
	/// <include file='doc\FlowControl.uex' path='docs/doc[@for="FlowControl.Call"]/*' />
	Call	= 2,
	/// <include file='doc\FlowControl.uex' path='docs/doc[@for="FlowControl.Cond_Branch"]/*' />
	Cond_Branch	= 3,
	/// <include file='doc\FlowControl.uex' path='docs/doc[@for="FlowControl.Meta"]/*' />
	Meta	= 4,
	/// <include file='doc\FlowControl.uex' path='docs/doc[@for="FlowControl.Next"]/*' />
	Next	= 5,
	/// <include file='doc\FlowControl.uex' path='docs/doc[@for="FlowControl.Phi"]/*' />
	/// <internalonly/>
	Phi	= 6,
	/// <include file='doc\FlowControl.uex' path='docs/doc[@for="FlowControl.Return"]/*' />
	Return	= 7,
	/// <include file='doc\FlowControl.uex' path='docs/doc[@for="FlowControl.Throw"]/*' />
	Throw	= 8,
}
}
