// ==++==
// 
//   
//    Copyright (c) 2002 Microsoft Corporation.  All rights reserved.
//   
//    The use and distribution terms for this software are contained in the file
//    named license.txt, which can be found in the root of this distribution.
//    By using this software in any fashion, you are agreeing to be bound by the
//    terms of this license.
//   
//    You must not remove this notice, or any other, from this software.
//   
// 
// ==--==
/*============================================================
**
**Class: OpCodeType
**
**Purpose: Exposes OpCodeType Attribute of IL .
**
** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT BY HAND!
** See clr\src\inc\opcodegen.pl for more information.**
============================================================*/
namespace System.Reflection.Emit {

using System;

/// <include file='doc\OpcodeType.uex' path='docs/doc[@for="OpCodeType"]/*' />
[Serializable]
public enum OpCodeType
{

	/// <include file='doc\OpcodeType.uex' path='docs/doc[@for="OpCodeType.Annotation"]/*' />
	/// <internalonly/>
	Annotation	= 0,
	/// <include file='doc\OpcodeType.uex' path='docs/doc[@for="OpCodeType.Macro"]/*' />
	Macro	= 1,
	/// <include file='doc\OpcodeType.uex' path='docs/doc[@for="OpCodeType.Nternal"]/*' />
	Nternal	= 2,
	/// <include file='doc\OpcodeType.uex' path='docs/doc[@for="OpCodeType.Objmodel"]/*' />
	Objmodel	= 3,
	/// <include file='doc\OpcodeType.uex' path='docs/doc[@for="OpCodeType.Prefix"]/*' />
	Prefix	= 4,
	/// <include file='doc\OpcodeType.uex' path='docs/doc[@for="OpCodeType.Primitive"]/*' />
	Primitive	= 5,
}
}
